### ISSUE TITLE
Add deoxy button to carb builders

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#100]
GMML can handle generating deoxy sugars like this:
DGlcpNAc[4D]b1-OH
Where this will delete the 4 oxygen of the GlcNAc. The nomenclature works the same as for derivatives. So instead of 4S for 4 sulfation, you have 4D for 4 deoxy. (Deoxy means delete the oxygen atom.)
Definitely discuss with Rob about how we want this presented on the page for the user. Maybe it's a distinct button from "Add Derivative", as conceptually it's removing rather than adding. Could also just be one of the things in the list of derivatives...

**Comment by danwentworthart** [comment]
There is already a Deoxy button that shows when we click Add Derivatives. Would you like "Add Derivatives" to say "Derivatize" for more clarity? Or am I misunderstanding your goal?

**Comment by danwentworthart** [comment]
I did test a request for 
DGlcpNAc[4D]b1-OH 
and it seems to hang on minimizing. Have you gotten past that without the website involved?

**Comment by danwentworthart** [comment]
Works ok as is.
