### ISSUE TITLE
Fix link to build via url

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#101]
On our home page we have a link on the side to "build via url" which directs to http://legacy.glycam.org/docs/custombuilders/quickstart_build-via-url/
Is it ok that we temporarily link to my eln site instead? This is the page I want to link to instead, it shows how to do it for our new site.
http://128.192.9.183/eln/oliver/2022/10/12/build-via-url/

**Comment by danwentworthart** [comment]
Done, but not distributed.
