### ISSUE TITLE
Slow-building structures + LiteMol loading

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/website#103]
CB Options page waits for a build response to render. Problem is that it can render before the default structure is ready.

A spinny wheel does show if the response is slow. I don't recommend changing that to wait for the build.

Instead, I recommend showing a spinny wheel in the place of the LiteMol viewer until the file exists, then load it.

**Comment by cexum** [comment]
Bug -- fails to visualize.

Feature -- Add a spinny-wheel.

**Comment by gitoliver** [comment]
I see spinny wheels now.
