### ISSUE TITLE
`Download All` button is accessible before all minimizations for all conformers is complete

### ISSUE THREAD

**Issue by Pshepp** [GLYCAM-Web/website#109]
**Tool:**
https://test.glycam.org/cb/download/

**Bug Description:**
When trying to build a sufficiently large structure where it takes a fair amount of time to finish each conformer minimization, and some conformer rows will be completed while others are not, the `Download All` button will not ensure all files have completed their minimization.

As each of the different types of minimization types complete, the `Download All` button will add what files have completed to its target thus users will download only a portion of the minimization files.

**To Reproduce:**

1. Enter a sufficiently large structure to build and go through the normal steps so you end up on the `download` page. This structure must be large enough to cause some conformer rows to complete but still have more conformers in the queue.
2. Pop open your browser developer tools and inspect the `Download All` button. The the href target will change from `#` to a download target before all conformer minimizations are complete and that target will allow for a download.

**Expected behavior**
The `Download All` button does not point to a valid file to download until all minimizations are complete.

**Device & OS Details**
Brave Browser 107.1.45.127 
Ubuntu 20.04.5 LTS x86_64

**Additional context**
This pattern is most likely present in other tools, but I did not go check them. Also keep in mind the `Download All` button is actually a dynamically updated `href`, so the `Download All` button is actually a link. 

Since the `Download All` is a link there is not real way to actually disable clicking on it, but there is some CSS+JS wizardry that I think can provide this functionality but it is probably not worth your time.

**Comment by cexum** [comment]
Was this seen in deployment, or in DevEnv?

Our next step will be to replicate, so can you please share the problematic sequence.

**Comment by gitoliver** [comment]
Could be difficult to reproduce and related to the status switching between "All complete" and "minimizing" I see happening. So if it goes to All Complete before it actually is, that would trigger the issue. Fixes to polling will fix this.
DNeup5Aca2-3DGalpAb1-4LFucpb1-6DGlcpNAcb1-6DAllpa1-6DAllpa1-OH
Could trigger it, but remember if you build it once then it exists and you won't see the issue twice. Changing the sequence slightly by converting a b1-6 to an a1-6 is possibly enough to trigger a new build.

**Comment by Pshepp** [comment]
We could just have a 2d bool array or something that lets us know what is completed. Since we dont really care about specifics (maybe we do? use a mapping standard container, basically a key:value pair dude. a `dict` is one for python) which when everything is complete we send a packet to the front end saying to enable the downloads button.

To reproduce isnt too hard if you have chem knowledge, just a big enough sequence will cause it but im a chimp with regards to chem lol

**Comment by Lachele** [comment]
You can also test this by removing all previously built sequences in your DevEnv or in the userdata for LiveTest.  

We need the status checking to evolve a bit.  We need each Entity that causes the generation of files to be able to tell when those files are complete.  This might not be possible for every single file, but we should be able to find ways to tell for groups of related files.  In this case, it is the mmservice/amber Entity that should have this knowledge.

**Comment by gitoliver** [comment]
I believe this is fixed.
