### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by Pshepp** [GLYCAM-Web/website#114]
**Is your feature request related to a problem? Please describe.**
A dark theme that looks good, insomniacs will love this

**Describe the solution you'd like**
Have the ability to switch between our current theme and a dark theme that is easy on the eyes

**Describe alternatives you've considered**
you can force dark theme with browser extensions, but something they look a bit off and also is not as convenient 

**Additional context**
A good example is the docker documentation site with their little slider at the top (https://docs.docker.com/)

**Comment by aniketdogra77** [comment]
hi I like to contribute on the issue . An alternative solution would be to use a browser extension to enable a dark theme, but this may not look as good or be as convenient as a built-in feature in the website or application.

**Comment by aniketdogra77** [comment]
can you pleaese provide more information how can i resolve this issue

**Comment by Pshepp** [comment]
Definitely appreciate the offer, but right now the styling bits of the stack are in our private repo, and we are in the middle of a fairly large live refactor so moving repos around will invite trouble. We do plan to make more of the stack publicly accessible in the future, and if we don't have this done by then, we would love help to take care of it.
