### ISSUE TITLE
The saved structure for DGlcpNAca1-OH is borked.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#120]
**Tool:**
Build DGlcpNAca1-OH

**Bug Description:**
The downloaded file looks like this too:
![image](https://user-images.githubusercontent.com/17079588/217316667-eb97cc8b-e631-43af-a3fd-c5dfe14c5245.png)

I will try deleting the database structure and see what happens. hint: 
https://glycam.org/json/download/pdb/text/9c489957-a610-4837-97db-75b9c7a7690d/structure/

**Comment by gitoliver** [comment]
Lachele we need to figure out if we want to purge the actual database. There are borked structures. This isn't the only one.

**Comment by danwentworthart** [comment]
I just built this on test.glycam.org and got the following. Is this issue resolved now, and can we close this ticket?

![IsItReallyBorked](https://github.com/GLYCAM-Web/website/assets/27075406/bdeb74a5-4c13-4897-a97f-9937b5cca9fe)
