### ISSUE TITLE
Download minimized structure button for sequence doesn't work

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#121]
**Tool:**
On actual: yearning yael build:
DManp[2Me,3Me]a1-4DManp[2Me,3Me]a1-4DManpa1-4DManpa1-4DManpa1-4DManpa1-4DManp[2Me,3Me]a1-4DManp[2Me,3Me]a1-4DManpa1-4DManpa1-4DManpa1-4DManpa1-4DManp[2Me,3Me]a1-4DManp[2Me,3Me]a1-OH

Click on Download minimized structure. You get a 500 error. The link is:
https://glycam.org/json/download/pdb/text/47edc3b0-7b58-44f1-82a3-796592fdc319/structure/

If you download the zip file, you can see that structure.pdb exists. I can build other structures and click on the button and get a pdb file to download. This was a new structure that I generated today.

**Comment by danwentworthart** [comment]
Fixed in commit #12e057143e48ae658f048e0441aa1b56eb3000ae 
Pushed to web-test.
