### ISSUE TITLE
Downloads page fails to download the pdb text file.

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/website#127]
**Tool:**
CB/GAG/etc....

**Bug Description:**
Download fails with a 500 error.

**To Reproduce:**
build something, and click PDB button in the downloads table.

**Expected behavior**
download the file

**Additional context**
This happens on Actual. It does not happen in the devEnv.

**Comment by danwentworthart** [comment]
I spotted the issue. This relates to the botched update of actual, a month ago. 

The issue does not exist in the devEnv. Predict the fix is to simply get Actual to use a more recent commit of the web-test branch.

To confirm the solution is present in a given branch, look at the following file:
V_2/Django/glycam-django/glycamweb/json_api/downlaods_manager.py

Problem is in this method:
_file_name_check()
```
2023-03-08 12:07:32 PM - json_api.downloads_manager - ERROR - Traceback (most recent call last):
  File "/website/glycam-django/glycamweb/json_api/downloads_manager.py", line 259, in _file_name_check
    file_name = "structure_" + pUUID + + ".pdb"
TypeError: bad operand type for unary +: 'str'
```
In the corrected version, you will not see "+ +" between "pUUID" and ".pdb"

**Comment by danwentworthart** [comment]
Spotted a bug that was waiting in line behind this. Fixed and pushed. We need to give time for Glyfinder to be fixed before actual can be updated. Leaving this ticket open until we can confirm all is well on actual after the update.

**Comment by danwentworthart** [comment]
With the above bug resolved, we are seeing very similar issues, as though the bug were not resolved at all. On looking deeper, I am finding the errors are different.

I captured a snippet of the logs describing that the min-gas.pdb file is not found, and maybe the error it throws causes a redirect, but should instead just log out a warning to the console?

I am also attaching the video of the bug for replication confirmation purposes.

```
2023-03-13 02:45:49 PM - json_api.downloads_manager - ERROR - Failed to download the zipped up pdb file: /website/userdata/sequence/cb/Builds/810ed389-7774-4ada-85ee-cc7ebcc0efd9/Existing_Builds/2ogg_3ogt_4ogt_6ogg/min-gas.pdb
2023-03-13 02:45:49 PM - json_api.downloads_manager - ERROR - Traceback (most recent call last):
  File "/website/glycam-django/glycamweb/json_api/downloads_manager.py", line 60, in download_pdb_text
    raise(FileNotFoundError(target_file))
FileNotFoundError: /website/userdata/sequence/cb/Builds/810ed389-7774-4ada-85ee-cc7ebcc0efd9/Existing_Builds/2ogg_3ogt_4ogt_6ogg/min-gas.pdb
```

https://user-images.githubusercontent.com/27075406/224804238-d76ec66b-3395-4c69-9097-769aeddf6cb6.mp4

**Comment by danwentworthart** [comment]
Of note, this has not been replicated in a local dev env. All captures are on test.glycam.org.

**Comment by Lachele** [comment]
I think this is fixed now.  Yes?

**Comment by cexum** [comment]
May I close this?

**Comment by cexum** [comment]
We have tested this fix on actual and it worked; closing ticket.
