### ISSUE TITLE
Bug with LIdopA[2S]a1-4DGlcpNS[6S]a1-4LIdopA[2S]a1-4DGlcpNS[6S]a1-OH

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#132]
**Tool:**
Carb builder

**Bug Description:**
I get a disaccharide in all downloaded files (I checked the mol2 after downloading everything) instead of a tetrasaccharide when I put the above sequence into glycam-web Zany-zorn. It is an existing build. The logs all contain the correct sequence, so I assume this was a gmml bug that got fixed, but perhaps it's a gmml bug that got fixed but now our stored structure is "polluted" on actual so I'm making it a website issue we need to check after migrating aimless-abbott to actual. The same sequence on test.glycam.org (aimless-abbott) works perfectly. 

**To Reproduce:**
Build via text: LIdopA[2S]a1-4DGlcpNS[6S]a1-4LIdopA[2S]a1-4DGlcpNS[6S]a1-OH
If you see two residues in litemol, i.e. two colored cubes inside a molecule instead of 4, it's wrong.
Good:
![image](https://user-images.githubusercontent.com/17079588/233953354-15478e89-4e1b-4036-8d65-eafa9c5e8d9c.png)
Bad:
![image](https://user-images.githubusercontent.com/17079588/233953431-3533f605-b642-4713-aa62-740743e19407.png)

**Comment by Lachele** [comment]
Thanks for the note.  We need to start a new set of cb data upon migration.

See also https://github.com/GLYCAM-Web/website/issues/126

**Comment by danwentworthart** [comment]
I just tested this on fear-falat, and I got 
![BugWithLIdopA](https://github.com/GLYCAM-Web/website/assets/27075406/43bb5b1a-a9e6-4e13-bb83-9c7def360711)

Am I correct that this issue is resolved, and the ticket can be closed now?
