### ISSUE TITLE
Glycam sequence request for 1-2 linked Sialic acid

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#135]
We have glycans in GlyGen that link two anomeric centers with each other
```
G38361UZ	DGalpNAca1-2DNeup5Aca2-OH
G69723YI	DGalpb1-2DNeup5Acb2-OH
```
In both cases the position 1 of GalNAc/Gal (anomeric carbon) links to position 2 of NeuAc (anomeric carbon). How would the correct glycam sequence look like for this case?

**Comment by edwardsnj** [comment]
I think these are correct GLYCAM transformations of bad underlying structures. When I use the GLYCAM tools to add Neu5Ac as the reducing end monosaacharide it is shown as "DNeup5Aca2-OH". I can then add a GalNAc but alpha-2 is not an allowed option. If I force it by editing the text, GLYCAM refuses to work with it. Nevertheless, the WURCS/GlycoCT sequence for this accession specifies alpha-2 linkage. *shrug*

**Comment by ReneRanzinger** [comment]
They are certainly chemically possible. 

Some bacteria structures (in CarbBank) also have anomer-anomer linkages. Although that usually does not involve Neu5Ac but Glc, Gal and therefore is a (1-1) linkage.

And there is always [alpha,beta-Trehalose](https://pubchem.ncbi.nlm.nih.gov/compound/alpha_beta-Trehalose).

**Comment by gitoliver** [comment]
G38361UZ	DGalpNAca1-2DNeup5Aca2-OH
G69723YI	        DGalpb1-2DNeup5Acb2-OH
These aren't quite right, the 2 position wouldn't have an OH. So in our nomenclature they would be:
DGalpNAca1-2DNeup5Aca
DGalpb1-2DNeup5Acb
But these are throwing errors. I'll look into this next week and report back.

**Comment by edwardsnj** [comment]
The PyGly code for GLYCAM sequences has a check for 1-to-1 monosaccharide pairs (to exclude them). I've updated this to check whether the link is between the ring_start number of the corresponding monosaccharides. This eliminates these cases (and a bunch of others, probably). These GLYCAM sequences will be dropped in the next glycan data release.

**Comment by gitoliver** [comment]
We can do other ano-ano linkages, for example:
DGlcpa1-2DFrufb
DFrufb2-1DGlcpa
Also there are sequences like this that aren't ano-ano, but excluding "1-1" would filter them:
LFucpa1-1DFrufb2-OME
