### ISSUE TITLE
Bug in building a sequence

### ISSUE THREAD

**Issue by HemanthReddy45** [GLYCAM-Web/website#136]
**Tool:**
Carbohydrate builder

**Bug Description:**
While building a branch through the carbohydrate builder the done button should be disabled until at least one residue is added.
Pleas Find the Attached snapshot of an example sequence where the done button is enabled which was supposed to be greyed.
![bug1](https://github.com/GLYCAM-Web/website/assets/43131256/d9bc218b-ae02-46b3-bb43-50eb2da03841)

**Comment by danwentworthart** [comment]
Fixed and distributed
