### ISSUE TITLE
Missing features in GLYCAM to fully support GlyGen glycans

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#140]
@edwardsnj and I did a test run with ~6,600 from GlyGen and had them evaluated (not build) by glycam. There are ~140 structures that failed the validation.

**Reason - Missing furanose monosaccharides**
- DAllf
- DAltf
- DFucf
- DGalf
- DGalfNAc
- DGlcf
- DGlcfNAc
- DGulf
- DIdof
- DManf
- DManfNAc
- DRhaf
- DTalf
- LAllf
- LAltf
- LFucf
- LGalf
- LGlcf
- LGulf
- LIdof
- LManf
- LRhaf
- LTalf

**Reason - Missing monosaccharide**
- DIdop
- LIdop

**Reason - GlcA with 6 linked Sulfate or Methyl**
* [G32430MQ](https://www.glygen.org/glycan/G32430MQ)
* [G73698CD](https://www.glygen.org/glycan/G73698CD)
* [G47519VR](https://www.glygen.org/glycan/G47519VR)
* [G77291EZ](https://www.glygen.org/glycan/G77291EZ)

**Other reasons:**
* #139 
* #138 

For now we will remove structures with these issues. If you are working on any of these please let us know so we can bring them back.

**Comment by gitoliver** [comment]
**Missing furanose monosaccharides and Missing monosaccharide**
We don't have parameters for these and won't anytime soon. A new release of GLYCAM that's in the pipeline might change that for some of them.

**GlcA with 6 linked Sulfate or Methyl**
We don't handle 6-linkages to GlcA or similar, the C6 is a carboxylate so there are two oxygens to chose from, plus we don't have parameters even if you specified.

Other issues were resolved on their own pages.
