### ISSUE TITLE
Having other download pages open messes with some of the structures in the libs. 

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#141]
**Tool:**
On test.glycam.org (aimless abbott) only, not on actual (Zany-Zorn)
https://glycam.org/lib/load/cfglibs/

**Bug Description:**
Click on page 14 and click on a glycan that doesn't have rotamers:
https://test.glycam.org/lib/show/cfglibs/None/14/
scroll down to the last one: DGalpNAc[3S]b1-4DGlcpNAc[3S]b1-OME
I get:
Captured by: [lib](https://test.glycam.org/lib/)
Error loading the CbProject: for the Downloads page get() returned more than one CbProject -- it returned 2!
Url is: https://test.glycam.org/error/lib/Error%20loading%20the%20CbProject:%20for%20the%20Downloads%20page%20get()%20returned%20more%20than%20one%20CbProject%20--%20it%20returned%202!

**This only happens if you have another download page open somewhere.**

**Comment by gitoliver** [comment]
This needs careful inspection, because closing the other page doesn't always fix the issue. Maybe caching is coming into it too.

**Comment by danwentworthart** [comment]
I just failed to replicate this. I vaguely remember addressing this in a refactoring pass months ago, so I will leave it open until @Oliver can confirm it is actually resolved. I believe the solution has been deployed to test.glycam.org at this point.

**Comment by danwentworthart** [comment]
I believe this is resolved in test.glycam.org. If I am incorrect, please open a new ticket, and capture the experience with the Jam software?
