### ISSUE TITLE
Download page polling saying that we can download files when minimization hasn't finished yet.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#142]
**Tool:**
DGalpNAc[4S]b1-4LIdopA[2S]a1-3DGalpNAc[4S,6S]b1-4DGlcpA[2S]b1-3DGalpNAc[6S]b1-4LIdopAa1-OME
Make small edits to create a new structure, eg delete a 6S or make the OME an OH, add a 6S where it isn't etc.

**Bug Description:**
I can download the rotamer info, see attached, that doesn't contain min-gas.pdb or min-gas.mol2. 
[df702e45-fb2a-4a37-9f01-4a7e3d649d77_structure.zip](https://github.com/GLYCAM-Web/website/files/11724762/df702e45-fb2a-4a37-9f01-4a7e3d649d77_structure.zip)

Happens on actual (Zany) and test (abbott).

**Comment by danwentworthart** [comment]
I'm failing to replicate this. Is it possibly addressed or can I get an assist on replication?

**Comment by gitoliver** [comment]
You fixed this.
