### ISSUE TITLE
Wonky Input Giving Useless error msg

### ISSUE THREAD

**Issue by Pshepp** [GLYCAM-Web/website#145]
**Tool:**
I tested this on the cb build via text tool but this issue is probably present in all of our tools where we take in user input.

**Bug Description:**
When inputting sequences I can include a `:` anywhere in the text and it borks while providing a not-useful error msg. We can begin attacking this by just making sure only expected characters are within the fields, while ignoring the pattern of the text, which can be done on the front end. Now, eventually we need to properly sanitize user inputs on our back end before we take em deeper into our server and code but that can be done later. 

**To Reproduce:**
Just go to https://test.glycam.org/txt/ throw in a sequence and add a colon wherever.

**Expected behavior**
Just a notification to the user they added bad characters. Now something we could do to make the site feel cleaner and be a bit more reactive is add in a small bit of js to the front end of our text fields that just checks if there are any characters we do not allow in the field then the text input box turns red so the user knows they entered something bad, and this would be running on the users browser itself. Maybe even have a msg pop up in red saying "Invalid character(s): <bad char here>" or something i dunno 

**Screenshots**
![image](https://github.com/GLYCAM-Web/website/assets/17117182/aa6c8fb0-a0ee-4c64-bc29-50a0221b3a11)
![image](https://github.com/GLYCAM-Web/website/assets/17117182/dbf78a28-8854-4eea-9a8e-1f75f9542198)

**Comment by Lachele** [comment]
Is this happening in gmml or is Django doing it?

**Comment by gitoliver** [comment]
GMML can throw a good error for this:
*********************
Building DManpa1-6Manpa1-:OH
*********************
Error thrown by the carbohydrateBuilder in gmml during construction was: Cannot create 3D structure as no GLYCAM residue code was found in the GMML metadata for residue: :OH


Need to dig a bit more, it seems like this message is always shown now if there is an error.

**Comment by Pshepp** [comment]
idk if this is resolved, but the other day i tried some bad inputs on cb build via text and it gave a decent errory so will leave it up to yall to close it if its done

**Comment by gitoliver** [comment]
DManpa1-6Manpa1-:OH is still giving:
There was a problem making the default sequence request: Error message not found.
on test and actual. I know Dan worked on this and we were getting error messages again in some cases, but it looks like it's not been fully resolved.

**Comment by danwentworthart** [comment]
Your call if you want to wait and close this when the fix is deployed, but the fix has been done.
When my latest work reaches a deployment, the sequence you are testing will give the following error:
![Error_Mngr](https://github.com/GLYCAM-Web/website/assets/27075406/9dafbbd4-78db-437c-aaa0-e5ee2de1db84)

**Comment by danwentworthart** [comment]
I'm not sure that is the best error message. But we have the infrastructure in place for gmml to say what it wants, and now it can change as you like without needing work in the website. I won't close this, in case anyone agree's with me that the following message I just got might not be the most clear communication:
My sequence: "DManpa1:-OH"
"Cannot create 3D structure as no GLYCAM residue code was found in the GMML metadata for residue: DManpa"

It is actually pretty great if I place that colon elsewhere: "DMan:pa1-OH"
"Cannot create 3D structure as no GLYCAM residue code was found in the GMML metadata for residue: DMan:pa"

Not sure if it would be easy to address, or if it is an acceptable solution as is.

**Comment by gitoliver** [comment]
This is a gmml issue now. 
DManpa1-6Manpa1-:OH
Good error:
Cannot create 3D structure as no GLYCAM residue code was found in the GMML metadata for residue: :OH
DManpa1:-OH
Bad error:
Cannot create 3D structure as no GLYCAM residue code was found in the GMML metadata for residue: DManpa
It should be showing the : i.e. "DManpa:" and not just "DManpa"
Worth keeping open and fixing when next doing stuff in the cb code.
