### ISSUE TITLE
Big structure giving time out error on dev and actual, builds fine in my local test branch env. 

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#148]
I get a 502 error when I try to build this on dev or actual:

DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4[DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-6]DGlcpa1-4[DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-6]DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-OH

It builds ok in my local test branch env.

**Comment by gitoliver** [comment]
Here are the outputs from my local env build:
https://drive.google.com/file/d/1KTjS1HC57lZNU_bVGJr43a0LoIFMmWC_/view?usp=drive_web

**Comment by danwentworthart** [comment]
This is a perfect case for a test aimed at deployments on test.glycam.org. 

The test needs to allow a long build process to have the full time it needs when all steps are taken. We miss things like this in the devEnv because builds are limited to a single step in that context.

**Comment by danwentworthart** [comment]
Confirmed working in test.glycam.org
