### ISSUE TITLE
Done button is enabled before the sequence was completely built

### ISSUE THREAD

**Issue by HemanthReddy45** [GLYCAM-Web/website#151]
**Tool:**
http://172.30.0.2/cb/
change the base url as per your environment.

**Bug Description:**
When building a sequence with a branch in it, the done button is enabled when there's nothing inside the branch. Ideally, it should be disabled until the sequence was fully built.

**To Reproduce:**
Please give us as many details as possible, so we can reproduce the bug. Bugs that cannot be reproduced are challenging to fix.

1. Go to '/cb'
2. build 'DTalpa1-6[]DTalpa1-OH'
3. See that done button is enabled even if nothing is added into the branch

![image](https://github.com/GLYCAM-Web/website/assets/43131256/bae23057-1157-457e-9aa1-7b4490cb18b5)

**Comment by danwentworthart** [comment]
Fixed and distributed.
