### ISSUE TITLE
nginx 504 Gateway Time-out happens for big carbs.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#155]
**Tool:**
Any carb builder on test.glycam.org.

**Bug Description:**
I get an nginx 504 Gateway Time-out for carbs with a lot (83 in this example) of residues. 

**To Reproduce:**
glycam.org/url/condensed/DAllpa1-4DGlcpa1-4DGlcpa1-4[3DManpa1-3DGalpa1-]<40>OH

**Expected behavior**
It should wait longer/forever for gems to finish building the carb and respond.

**Importance** 
Address after Oct 2023 GlycoMIP meeting, but make sure developers are aware of it so can respond to questions about it. The webpage needs to wait indefinitely/longer, and speedups in gmml are ready to be pushed to the test site.

**Comment by danwentworthart** [comment]
Adding Andrew to the Assignees list, for Nginx guidance.

**Comment by danwentworthart** [comment]
I see what is happening here. Prioritizing this bug fix for this week. The new pattern of submitting the request via JavaScript instead of Python, on cb Options, has not been implemented in the build Via URL endpoint. This is an easy fix, but will not be available until the next update of test.glycam.org.

**Comment by gitoliver** [comment]
Ok so to confirm when you do:
test.glycam.org/url/condensed/DAllpa1-4DGlcpa1-4DGlcpa1-4[3DManpa1-3DGalpa1-]<40>OH
You see that it's showing json?:
![image](https://github.com/GLYCAM-Web/website/assets/17079588/01c38bd8-b477-49ea-b3af-48c9e8e44a0b)

**Comment by danwentworthart** [comment]
That is what I see, and know how to fix. Finishing a task prioritization pass, but this will be the first issue when that is complete.

**Comment by danwentworthart** [comment]
Fixed and distributed, but not deployed. Will be available in the next release cycle. Commit hash: 1faf9cc1d788301bf3f491682a0ae982706acaa1

I think I should leave this open until it is deployed.

**Comment by danwentworthart** [comment]
I generated this on test.glycam.org. What a cool structure! Closing the ticket.
![BUGFIX: 155](https://github.com/GLYCAM-Web/website/assets/27075406/2be9c892-5458-4266-897b-ac8b0ac6c00a)
