### ISSUE TITLE
Page Responsiveness(pb app)

### ISSUE THREAD

**Issue by HemanthReddy45** [GLYCAM-Web/website#159]
**Tool:**
polybuilder
**Bug Description:**
the repeats block in the attached image is not well aligned when the resolution is set to mobile device

**To Reproduce:**
go through the following page and then chrome dev tools to set the resolution as 'mobile'(may be an iPhone 12 Pro)

![image](https://github.com/GLYCAM-Web/website/assets/43131256/a29f92ac-6361-4f96-b5d9-9f64d362d3f2)

**Comment by danwentworthart** [comment]
Fixed in commit #e5e7225ff97b2ed2bb2d3e0cff02da2d5eb74d43
