### ISSUE TITLE
Example, copy-able sequences in build-via-text tool

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#173]
glycam.org/txt would be better with examples.
**Describe the solution you'd like**
We have all this whitespace below the text entry box:
![image](https://github.com/GLYCAM-Web/website/assets/17079588/09694293-e1e2-4f44-b884-43cf54ee4d45)

Can you add the following text, ensuring that it's easy to double click on a sequence and copy/paste each sequence into the box, or directly insert it into the box for the user upon a button click? Do not automatically submit anything, give them the opportunity to edit the text.
**Examples**:
Monosaccharides:
DManpa1-OH
Oligosaccharides:
DNeup5Aca2-6DGalpb1-4DGlcpNAcb1-OME
Branched Oligosaccharides:
DGlcpNAcb1-6[DGlcpNAcb1-2]DManpa1-6[DGlcpNAcb1-2[DGlcpNAcb1-4]DManpa1-3]DManpb1-4DGlcpNAcb1-4[LFucpa1-6]DGlcpNAcb1-OH
Anomeric-Anomeric linkages:
DFrufb2-1DGlcpa
Repeating units:
[4LIdopA[2S]a1-]<5>OME
DGalpa1-4[4DManpa1-]<5>3DGlcpa1-OME
Branches in repeating unit:
DGlcpa1-4[4DGlcpa1-]<4>2DGlcpa1-4[4DGlcpa1-6[LFucpa1-2]DManpa1-]<2>OH
Nested repeats:
[4DGlcpa1-]<2>2DGulpa1-4[4DAllpa1-6[4DGalpa1-]<2>4DManpa1-]<2>3DManpa1-2[4DAllpa1-6[[4DGalpa1-]<3>4]DManpa1-]<3>OH

**Comment by danwentworthart** [comment]
This has been done, but I won't close the ticket. We can always add more, and if you comment here, I will get an email notification. Request away!
