### ISSUE TITLE
New Carb builder interface can't return from editing terminal. 

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#179]
**Tool:**
https://glycam.org/cb/ Carb builder on actual

**Bug Description:**
After editing the terminal the Done button is greyed out. I can't do anything except continue with adding more linkages:
![image](https://github.com/GLYCAM-Web/website/assets/17079588/b7acd25d-f776-407f-b0f3-7f61e844659f)

What if I wanted to build just DManpa1-OME?

**To Reproduce:**
Click on a monosaccharide. Click on Edit Terminal. Change to a different terminal. You cannot do anything from there except extend the chain.

**Expected behavior**
The Done button needs to be active after editing the terminal.

**Comment by danwentworthart** [comment]
Fixed and pushed in web-test commit 3078369

**Comment by danwentworthart** [comment]
Missed the close button. Issue resolved.
