### ISSUE TITLE
GP complains about suspicious behavior when uploading a pdb file - instead of loading step 2.

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/website#18]
**Tool:**
GlycoProtein Builder.  http://172.18.0.8/gp/

**Bug Description:**
Step 2 will not load when I upload a pdb. Shows a SuspiciousFileOperation error,

**To Reproduce:**

1. Go to .../gp
2. Click on 'Choose File'
3. Select the GlycoProtein_beads.pdb file
4. Click submit.

**Expected behavior**
One would expect step 2 to load.

**Screenshots**
![GP-UploadError](https://user-images.githubusercontent.com/27075406/55890481-bf9a1b00-5b80-11e9-81d1-d2eefab9e1c2.png)

**Device & OS Details**
Linux in a VM on a Mac. Dev env.

**Comment by gitoliver** [comment]
Not sure if this is legacy or the draft of the new gp builder we had up for a while. Either way it's not relevant anymore.
