### ISSUE TITLE
Show full sequence on download page for repeat unit structures, or allow it to be displayed as an option. Maybe at the bottom of the page so it can overrun?

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#186]
Here:
![image](https://github.com/GLYCAM-Web/website/assets/17079588/311a4b19-52eb-4788-a0db-6248a87d1579)
Rob wants to see the full sequence so he can copy it and edit parts of it. Even if it's crazy long.

**Comment by danwentworthart** [comment]
This new feature was added such that only polysaccharides with repeat units will see the Expanded Sequence display down at the bottom of the page. This has been added and distributed, but not deployed.
Commit: a776bd52bc90de13cf86efe28e3092a50b226186
