### ISSUE TITLE
Building two carbohydrates in different tabs of the same browser gives you incorrect results.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#187]
**Tool:**
glycam.org/txt [gratitude-giacometti]

**Bug Description:**
Building two carbohydrates at the same time gives you the wrong structure. See video where I request 199 and 50, when the 50 finishes the 199 goes to a download page where I can see the 50 structure.

https://github.com/GLYCAM-Web/website/assets/17079588/a9de8132-9f3c-49d7-88c3-b0f877844c53

**To Reproduce:**
Go to glycam.org/txt. Enter something that will take a while to complete like 
[4LIdopAa1-]<249>OME
Open a new tab and build something that will be finish faster like:
[4LIdopAa1-]<49>OME

If you can't reproduce try changing the sequence as it may already exist.

Notice that if the second one finishes before the first one, the first one shows the second one's structure, even though the download URLs are different. I do not know where the mix-up is happening (gems/website)

**Comment by gitoliver** [comment]
Update: actually whatever page updates first when both are waiting on a response (or whatever), both pages will be converted to the most recently updated one. So the smaller/faster structure can become the larger one.

**Comment by danwentworthart** [comment]
This issue is in the queue, but I am making active progress on it between other tasks. I understand the problem, and am designing a solution.

**Comment by danwentworthart** [comment]
Fixed locally and pushed. Won't close till I can verify in test.glycam.org.
Commit: ac3e86fef7e326032c70fb6525c294cd3b675c4b

**Comment by gitoliver** [comment]
Looks fixed in test.glycam.org.

**Comment by danwentworthart** [comment]
Closing ticket.
