### ISSUE TITLE
DFrupb2-1DFrupa2-OH does not build on carb builder

### ISSUE THREAD

**Issue by holmess2013** [GLYCAM-Web/website#189]
Using the carbohydrate builder on actual, I've tried building some fructose sugars. A simple one that I haven't been able to build successfully is a fructose disaccharide: DFrupb2-1DFrupa2-OH. It just stays buffering.

To reproduce, you simply:
1) Get on the carb builder on actual
2) Click fructose --> fructose again --> select a B 2-->1 linkage
3) Click Done.

**Comment by holmess2013** [comment]
Very good!

**Comment by gitoliver** [comment]
Check in dev env and report back

**Comment by holmess2013** [comment]
Just started up the Dev Env and it still won't build in the carb builder. However, in hindsight this bug isn't that important if we're going to change the default ring type for fructose anyway. Who the hell would want to build a polymer of fructoses in the pyranose form??? The good news is the exact same sequence converted to the "f" ring type builds fine: DFrufb2-1DFrufa2-OH. Forgive me for bringing up this barely significant bug.

**Comment by gitoliver** [comment]
Closing issue as it bifurcated and became confusing. Follow https://github.com/GLYCAM-Web/gmml/issues/171 for  DFrupa2-1DFrupa2-OH not building and https://github.com/GLYCAM-Web/website/issues/190 for the website isn't showing errors from GMML.
