### ISSUE TITLE
Error messages are not shown to user

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#190]
Put random text into glycam.org/txt and you wait for a response forever:
https://jam.dev/c/ce0996d4-b5a3-43b6-9053-4ae1aa6ee281
Gmml does throw an error. 

Dan you did fix something like this before: https://github.com/GLYCAM-Web/website/issues/145
But this time it's different, it seems to be waiting on the response now, whereas before it was saying that there is an error, but not showing the gmml message.

I reproduced this on actual, swarm test and in my local dev env.

**Comment by danwentworthart** [comment]
Thank you for the amazing ticket. Deeply appreciate the Jam. I will look into this.

**Comment by danwentworthart** [comment]
Fixed and pushed to web-test.  a252dcec2c5dfc87452730b162119980f84284b1
