### ISSUE TITLE
Evaluation and build IDs changing in new tabs

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#194]
test.glycam.org

https://jam.dev/c/232e300f-e5e8-437c-8c0e-077519719d17

If you build a structure with options you get an options page with a link:
https://test.glycam.org/cb/options/f5d5855a-ca68-4c7c-b1df-03147e5d9cb9/
On the page it shows e.g:
User Project ID: f5d5855a-ca68-4c7c-b1df-03147e5d9cb9
Evaluation pUUID: 38c857d0-edb9-42bb-a86a-d84a4bb101ff
If you visit again the same link:
User Project ID: f5d5855a-ca68-4c7c-b1df-03147e5d9cb9
Evaluation pUUID: f102fc3c-c696-4f9b-8c74-8eddef08d547

Same when you go to the downloads page
https://test.glycam.org/cb/download/f5d5855a-ca68-4c7c-b1df-03147e5d9cb9/
If you're going there via a copied link you get a blank pUUID, and a unique Evaluation pUUID

That might be expected behavior, not sure. Edit ignore part here I deleted about the options link. I messed up.

**Comment by danwentworthart** [comment]
Fixed but not yet distributed. Commit # 56977bfeb924111b781716f5abcf23a70082ae1b

**Comment by danwentworthart** [comment]
Deployed to test.glycam.org
