### ISSUE TITLE
Front page clean up suggestions

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#197]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/GLYCAM-Web/website/assets/17079588/4509b92b-a350-4c07-aa38-0cdc9def8163)

**Describe the solution you'd like**
1) The GlycoMIP icon is squashed vertically. Can it maintain whatever aspect ratio it has here: https://glycomip.org/

2) While the bar at the top exists, these should be removed from the list on the left:
[About](http://glycam.org/docs/aboutus/)
[News](http://glycam.org/docs/news/)
[Help](http://glycam.org/docs/help/)
[Documentation](http://glycam.org/docs/)
[Legacy](http://legacy.glycam.org/)

3) Note: Publication-Related Materials is only on the left, not in the Tools dropdown menu from the bar. 

4) The spinning molecule was cool and handy for explaining what we did to people I meet at conferences. Can it return on the right in the space beneath "Interested in Modeling Glycomaterials?" 
![image](https://github.com/GLYCAM-Web/website/assets/17079588/945e3486-0efe-4664-9e9d-e5001e5cfac6)

**Comment by danwentworthart** [comment]
I added the molecule back in commit #684081bdc35e2133a589f6e340ebe3baae8c587b

**Comment by danwentworthart** [comment]
Added the publication related materials  link to the navbar in commit #88f3690a4db76de38607f6d76beecebe16f67927

**Comment by danwentworthart** [comment]
Footer Icon size adjustments for both NIH and GlycoMIP in commit #9c8a8131c0127f953f809b2c73f6f154e9180116

**Comment by danwentworthart** [comment]
Top section of side bar removed in commit: #7a0c2de237d3774158f81cf71fc0b18303bc67cd

**Comment by gitoliver** [comment]
Thanks!
