### ISSUE TITLE
The naming and descriptive language of the carbohydrate builders is confusing

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#198]
**Is your feature request related to a problem? Please describe.**
The naming and language of the carbohydrate builders is confusing. The use of the word "legacy" now that we have a legacy site, is unperfect. https://test.glycam.org/portal/scenario_page/carbbuilders

Also what is going on with these button widths?
![image](https://github.com/GLYCAM-Web/website/assets/17079588/4e81aedf-124d-450b-8120-0d24841a8772)

**Describe the solution you'd like**
Carbohydrate Builder (build left-to-right)
Carbohydrate Builder (build right-to-left)
Extra text for both: Assemble a glycan by connecting monosaccharides.

i.e. remove the "This is the legacy tool. " and "This new tool is still in development."
 
 If it's not single source, remember to update the text too: https://test.glycam.org/portal/scenario_page/md

**Comment by danwentworthart** [comment]
Btn sizing and content edits all made, but not yet deployed to production. 

commit #db34817f250d2d858a4abdf34b85c7a1594383dd

**Comment by danwentworthart** [comment]
Done and present in commit: #91afe3c3a4251caeeed347fde502eab62f5f8788
Verified on test.glycam.org.
