### ISSUE TITLE
Additional bond when trying to build Heparan Sulfate polysaccharide using repeat unit syntax

### ISSUE THREAD

**Issue by holmess2013** [GLYCAM-Web/website#201]
In the DevEnv, I tried updating the repeat unit for HS1 to Rob's liking, and then entering that into the build via text tool to see if I can get a structure. A structure is generated for [4DGlcpAb1-4DGlcpNSa1-]<2>OH but it is making an additional bond between repeat units that shouldn't be there:

https://jam.dev/c/908084cd-8343-4c33-89f4-f3e9f1648b65

**Comment by gitoliver** [comment]
There are two entangled issues here. 
1) GMML is not producing a good default structure for the a1-4 linkage to GlcA.
2) The website is saying Minimized = Yes in MolStar when it's still showing the default structure. This is bad.

**Things to do**:
GMML should produce better default structures. I suspect Tobias may have fixed this already in gmml2, but we don't have a timeline for it integrating into the website until Preston finishes the gmml2 wrap. 
The website should display the minimized one as soon as it's available (that is what we've always attempted to do) and better tie the messaging in MolStar to the correct structure being displayed. If that gets fixed we can likely say this is good enough for now.


Here is the jam where I discuss: https://jam.dev/c/1b221dd7-8c75-4449-9b85-113f84765027. Note that I discuss another issue I'm having too, but ignore that for this context.

**Comment by gitoliver** [comment]
Both of these issues are resolved on glycam.org.

GMML produces good default shapes now. Molstar is correctly saying minimized=false.
