### ISSUE TITLE
Hover text on button in Polylib is incorrect

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#203]
https://jam.dev/c/dac97dbf-950f-4c75-b8e8-b1287405cd49

Go to https://glycam.org/pb/lib/ and hover over the View 3D Model button. The text is about searching the pdb. The hover text should say e.g.: generate 3D structure.

**Comment by danwentworthart** [comment]
Corrected but not deployed. Commit: 3a2539bbb3640defa1eb94bfcd5f6f5862ba8e7a
