### ISSUE TITLE
Polylib is returning incorrect structures. Suspected problem with stored structures.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#204]
Jam here: https://jam.dev/c/ebe0f5af-2bb4-43ba-bb73-42dcc94c7583

If you go to https://glycam.org/pb/lib/ and click on cellulose, it correct requests [4DGlcpa1-]<10>OH which is expanded to:

DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-OH

However what I see in the 3D structure is the b version, i.e. it's showing the default structure for [4DGlcp**b**1-]<10>OH and not [4DGlcp**a**1-]<10>OH. It also never minimizes and is stuck for more than 10mins.

https://glycam.org/cb/download/8405655f-49c3-4723-bbdb-7438b808c2a8/

User Project ID: 8405655f-49c3-4723-bbdb-7438b808c2a8
Evaluation pUUID: cbeb41e9-9af7-4ffd-8abc-878821d6d4dc
Build pUUID: 162c446e-e007-46ac-886d-a032127e9cfc

**More diagnosis**:
I was able to build [4DGlcpa1-]<19>OH. I got the correct 3D structure and was able to download the completed structure after energy minimization. So the site is working. GMML is working. I think the issue is that the stored structure we have for this got corrupted somehow. Also, everything works correctly on test.glycam.org.

**Solutions**:
Can someone go look at those builds and confirm? Maybe try diagnose how this happened?
Can we backup the current database on actual and start fresh? I suspect there may be more corruption we are unaware of.

**Comment by Lachele** [comment]
Was the userdata folder supposed to have been remade starting July 2?

**Comment by Lachele** [comment]
Somehow, a beta structure was requested, but it somehow morphed into alpha.  

Note that this is supposed to be the raw request from the website.  It lists both alpha and beta.  Apologies for the minified json.

`cat logs/request-raw.json 
{"entity": {"type": "Sequence", "services": {"build": {"type": "Build3DStructure"}}, "inputs": {"sequence": {"payload": "DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-OH"}}}, "prettyPrint": "True", "mdMinimize": "True", "project": {"id": "6231ab45-5ecb-4d55-be20-d2cd182c64f5", "pUUID": "94244018-9855-4086-8beb-94c625fb7695", "title": "", "comment": "", "timestamp": "2022-02-08T17:26:33.701357", "gems_timestamp": "2022-02-08T17:26:33.701357", "project_type": "cb", "parent_entity": "Sequence", "requested_service": "Build3DStructure", "entity_id": "sequence", "service_id": "cb", "filesystem_path": "/website/userdata/", "compute_cluster_filesystem_path": "", "service_dir": "/website/userdata/sequence/cb", "project_dir": "/website/userdata/sequence/cb/Builds/94244018-9855-4086-8beb-94c625fb7695", "logs_dir": "/website/userdata/sequence/cb/Builds/94244018-9855-4086-8beb-94c625fb7695/logs", "requesting_agent": "", "has_input_files": "False", "site_version": "4af588ae933ced8c498a7724dd3180be11ada2b6", "site_branch": "web-test", "site_code_name": "petulant-paeff", "gems_version": "a3f0706143be6fedced37868b81dde074148edaf", "gems_branch": "gems-test", "md_utils_version": "589abe37c358b65119194ec8859d85aea3cadcf4", "md_utils_branch": "md-test", "gmml_version": "1dff0c0171f67803a0a361abe4b7612fed4ef0f5", "gmml_branch": "gmml-test", "gp_version": "", "gp_branch": "", "site_mode": "SWARM", "site_host_name": "glycam.org", "versions_file_path": "/website/userdata/VERSIONS.sh", "host_url_base_path": "https://glycam.org", "download_url_path": "https://glycam.org/json/download/sequence/cb/94244018-9855-4086-8beb-94c625fb7695/", "force_field": "default", "parameter_version": "default", "amber_version": "default", "json_api_version": "0.0.1", "django_project_id": "", "app": "project", "sequence_id": "f38ecf92-06fb-5a38-831e-624a7f6e1959", "sequence_path": "/website/userdata/sequence/cb/Sequences/f38ecf92-06fb-5a38-831e-624a7f6e1959", "indexOrderedSequence": "DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-OH", "seqID": "f38ecf92-06fb-5a38-831e-624a7f6e1959", "selected_rotamers": ""}}`

**Comment by Lachele** [comment]
So... yes, the structure is wrong somehow.  But, I'm not sure where the wrong is happening.  I can delete all the alpha and beta structures for this, but I can't guarantee it won't come back. 

Did you say it seems on on Test?

**Comment by Lachele** [comment]
Note the site codename...

**Comment by Lachele** [comment]
It seems to be working now.  I tested DManpa and a branched, sialylated molecule from the libraries.  I got structures for each that looked normal.  i did not check in great detail (e.g., I did not make sure that every residue has the correct chirality).

**Comment by Lachele** [comment]
I also built a 10-mer cellulose fragment since this ticket references the polybuilder.  The anomeric positions are beta, as expected.  I still did not check in great detail.

**Comment by gitoliver** [comment]
Glycam actual is now building correctly.
https://glycam.org/cb/download/95677ea8-3a75-4765-8916-98735062622a/

For posterity: 
Lachele: "Right now, Actual is using a folder that we never use to store structures.  It's just the "userdata" folder.  I suspect something is wrong. For sanity and versioning purposes we always name the folder something like:  userdata-start-gratitude-giacometti. That pattern has not been followed.  The site possibly works.  But, it makes me suspect that things might be weird."

So the site was deployed to use the wrong user folder. We suspect some clobbering/corruption of existing builds was present in that user folder. The userdata folder contains builds from as far back as 2019, but we don't know exactly how the clobbering originally occurred. It may have been fixed already, or may repeat at some point in the future. 

We saw requests like this where the sequence payload is different from the index ordered:

```
cat logs/request-initialized.json 
{
  "timestamp": null,
  "entity": {
    "entityType": "Sequence",
    "requestID": null,
    "services": {
      "build": {
        "typename": "Build3DStructure",
        "givenName": null,
        "myUuid": null,
        "inputs": null,
        "options": null
      }
    },
    "responses": null,
    "resources": null,
    "notices": null,
    "options": null,
    "inputs": {
      "sequence": {
        "payload": "DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-4DGlcpb1-OH",
        "sequenceFormat": "GlycamCondensed"
      },
      "sequenceVariants": null,
      "systemSolvationOptions": null,
      "geometryOptions": null,
      "buildOptions": null,
      "evaluationOptions": null,
      "drawOptions": null
    },
    "outputs": null
  },
  "project": {
    "pUUID": "94244018-9855-4086-8beb-94c625fb7695",
    "title": "",
    "comment": "",
    "timestamp": "2022-02-08T17:26:33.701357",
    "gems_timestamp": "2022-02-08T17:26:33.701357",
    "project_type": "cb",
    "parent_entity": "Sequence",
    "requested_service": "Build3DStructure",
    "entity_id": "sequence",
    "service_id": "cb",
    "filesystem_path": "/website/userdata/",
    "compute_cluster_filesystem_path": "",
    "service_dir": "/website/userdata/sequence/cb",
    "project_dir": "/website/userdata/sequence/cb/Builds/94244018-9855-4086-8beb-94c625fb7695",
    "logs_dir": "/website/userdata/sequence/cb/Builds/94244018-9855-4086-8beb-94c625fb7695/logs",
    "requesting_agent": "",
    "has_input_files": false,
    "site_version": "4af588ae933ced8c498a7724dd3180be11ada2b6",
    "site_branch": "web-test",
    "site_code_name": "petulant-paeff",
    "gems_version": "a3f0706143be6fedced37868b81dde074148edaf",
    "gems_branch": "gems-test",
    "md_utils_version": "589abe37c358b65119194ec8859d85aea3cadcf4",
    "md_utils_branch": "md-test",
    "gmml_version": "1dff0c0171f67803a0a361abe4b7612fed4ef0f5",
    "gmml_branch": "gmml-test",
    "gp_version": "",
    "gp_branch": "",
    "site_mode": "SWARM",
    "site_host_name": "glycam.org",
    "versions_file_path": "/website/userdata/VERSIONS.sh",
    "host_url_base_path": "https://glycam.org/",
    "download_url_path": "https://glycam.org/json/download/sequence/cb/94244018-9855-4086-8beb-94c625fb7695/",
    "force_field": "default",
    "parameter_version": "default",
    "amber_version": "default",
    "json_api_version": "0.0.1",
    "django_project_id": "",
    "app": "project",
    "notices": [],
    "sequence_id": "f38ecf92-06fb-5a38-831e-624a7f6e1959",
    "sequence_path": "/website/userdata/sequence/cb/Sequences/f38ecf92-06fb-5a38-831e-624a7f6e1959",
    "indexOrderedSequence": "DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-4DGlcpa1-OH",
    "seqID": "f38ecf92-06fb-5a38-831e-624a7f6e1959",
    "selected_rotamers": ""
  },
  "prettyPrint": true,
  "mdMinimize": true,
  "options": null,
  "notices": []
}(
```
