### ISSUE TITLE
Remove Ido from the Carb builder.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#208]
**Is your feature request related to a problem? Please describe.**
Remove the greyed out Ido button from the Carb builder.
This should not exist anymore:
![image](https://github.com/user-attachments/assets/f1ec2ee0-ba3d-48fd-ae83-66d8cf5d6290)

**Comment by danwentworthart** [comment]
Done, and pushed, but not yet deployed: commit#: c2933f607c489eb970e56912c61857c00b0a6f04
