### ISSUE TITLE
Glycoprotein Builder Minimization Problem

### ISSUE THREAD

**Issue by muslphlvn** [GLYCAM-Web/website#22]
Hi, 
There is a problem with the glycoprotein builder. The process is getting stuck in step 4 and cannot create a model.

**Comment by gitoliver** [comment]
Can you supply a pdbid (e.g. 1rvx) and what glycans you are trying to attach to where? If you can attach your pdb file here please do.

Sometimes there's overlaps it can't resolve, but can't say much more without more details from you.

**Comment by muslphlvn** [comment]
I have attached the zip file of the 3D structure. You can find the glycosylation residues and attached glycans in the jpg file.
[siglec_ref_glycam.zip](https://github.com/GLYCAM-Web/website/files/4640694/siglec_ref_glycam.zip)
![Residues and Glycans](https://user-images.githubusercontent.com/65504462/82155645-0fb4d800-987f-11ea-8560-e26f13acaad9.jpg)

But the problem is not unique for this structure.

**Comment by gitoliver** [comment]
We can't fix the legacy gp builder so closing this. If anyone finds it you can try deleting parts of your structure until you get something that works. Downloading without minimization to see what is there is also a good idea. If there are large overlaps minimization will not resolve them, and can fail in different ways.
