### ISSUE TITLE
API: Unexpected response for invalid JSON

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#23]
**Bug Description:**
Using https://dev.glycam.org/json/ to generated PDB files programmatically. If the input is an invalid JSON the server sends not a JSON response (as expected) but HTML code.

**Expected behavior**
JSON response with an error description.

**Comment by danwentworthart** [comment]
What input did you use to generate this error? It does catch many errors, though errors are possible that have not been tested for. A description, or copy of the input used to generate the error will be helpful in replicating and testing.

**Comment by danwentworthart** [comment]
I tried very hard to provide a solution for this. Unfortunately, I think it is beyond the scope of what I can do. It is my understanding that curl expects to be used to get web pages, so when curl is the thing that captures an error, such as malformed json, it returns its responses in raw html. 

If I am incorrect about this, I will be happy to reopen this issue and dig in again.

**Comment by ReneRanzinger** [comment]
This problem is unrelated to curl and persists in the current version as well. If I am sending an invalid JSON to the webservice (I am using a JAVA client not curl). The response is an HTML file.

Input to webservice:

`{"entity":`

Response is attached

[response.html.txt](https://github.com/GLYCAM-Web/website/files/7198465/response.html.txt)
.

**Comment by Lachele** [comment]
It's sending back html for the home page.  We can fix this.

**Comment by danwentworthart** [comment]
When this bugfix is distributed, invalid input should receive some variant of the following response:

{"entity": {"responses": [{"FrontEndNotice": {"type": "error", "notice": {"code": "400", "message": "There was a problem parsing the json data: Expecting value: line 1 column 16 (char 15)"}}}]}}

**Comment by danwentworthart** [comment]
I have tested the bugfix on two different machines now. They both succeeded. I have pushed the fix. It will be included the next time we update test.glycam.org. It will need vetting before it is made available in dev.glycam.org.

**Comment by ReneRanzinger** [comment]
@danwentworthart Is there a reason that this is "FronEndNotice" object inside the responses array? Other errors (e.g. invalid sequence) result into an "Error" object. It seems they are similar (e.g. user provided invalid json, user provided invalid Glycam format):

```
{
   "entity":{
      "type":"GRPC",
      "responses":[
         {
            "Error":{
               "respondingService":"JSONServer",
               "notice":{
                  "type":"Exit",
                  "code":"9",
                  "brief":"HaveStderr",
                  "message":"Process returned 0 as exit status, but also returned standard error."
               },
               "options":{
                  "osExitCode":"None",
                  "theStandardError":"b'Exception thrown in condensedSequence constructor. Look in the response object.\\n'",
                  "theStandardOutput":"b'the transaction is : \\n<gemsModules.sequence.io.Transaction object at 0x7fb381ccb290>\\n{\"timestamp\": null, \"entity\": {\"entityType\": \"Sequence\", \"requestID\": null, \"services\": {\"build\": {\"typename\": \"Build3DStructure\", \"givenName\": null, \"myUuid\": null, \"inputs\": null, \"options\": null}}, \"responses\": null, \"resources\": [], \"notices\": null, \"options\": null, \"inputs\": {\"sequence\": {\"payload\": \"A-R-R123\", \"sequenceFormat\": \"GlycamCondensed\"}, \"sequenceVariants\": null, \"systemSolvationOptions\": null, \"geometryOptions\": null, \"buildOptions\": null, \"evaluationOptions\": null, \"drawOptions\": null}, \"outputs\": {\"sequenceEvaluationOutput\": {\"sequenceIsValid\": false, \"sequenceVariants\": null, \"evaluationOptions\": {\"validateOnly\": false, \"evaluateForBuild\": true, \"noBuild\": false}, \"buildOptions\": null, \"drawOptions\": null}, \"structureBuildInfo\": null}}, \"project\": {\"pUUID\": \"5be5a7e1-32fa-4cb6-8ba4-3eb93023bb68\", \"title\": \"\", \"comment\": \"\", \"timestamp\": \"2021-09-20T15:20:10.427006\", \"gems_timestamp\": \"2021-09-20T15:20:10.427006\", \"project_type\": \"cb\", \"parent_entity\": \"Sequence\", \"requested_service\": \"Build3DStructure\", \"entity_id\": \"sequence\", \"service_id\": \"cb\", \"filesystem_path\": \"/website/userdata/\", \"compute_cluster_filesystem_path\": \"\", \"service_dir\": \"/website/userdata/sequence/cb\", \"project_dir\": \"/website/userdata/sequence/cb/Builds/5be5a7e1-32fa-4cb6-8ba4-3eb93023bb68\", \"logs_dir\": \"/website/userdata/sequence/cb/Builds/5be5a7e1-32fa-4cb6-8ba4-3eb93023bb68/logs\", \"requesting_agent\": \"\", \"has_input_files\": false, \"site_version\": \"e58620687f0254e974a39ee5f34233562227b16e\", \"site_branch\": \"master\", \"gems_version\": \"9d38c3f34c27f72a3c7972d9df1d6db1641b1f0f\", \"gems_branch\": \"gems-dev\", \"md_utils_version\": \"4e0395c9a9472ed7a957268350f7bacdf77196c8\", \"md_utils_branch\": \"main\", \"gmml_version\": \"5ed98ccaba7902bd95a17722b96a148121ecb621\", \"gmml_branch\": \"gmml-dev\", \"gp_version\": \"0228f03c36aa44a731abfcb387cedd4069558a61\", \"gp_branch\": \"stable\", \"site_mode\": \"SWARM\", \"site_host_name\": \"dev.glycam.org\", \"versions_file_path\": \"/website/userdata/VERSIONS.sh\", \"host_url_base_path\": \"https://dev.glycam.org\", \"download_url_path\": \"https://dev.glycam.org/json/download/sequence/cb/5be5a7e1-32fa-4cb6-8ba4-3eb93023bb68/\", \"force_field\": \"default\", \"parameter_version\": \"default\", \"amber_version\": \"default\", \"json_api_version\": \"\", \"django_project_id\": \"\", \"notices\": [], \"sequence_id\": \"\", \"sequence_path\": \"\", \"indexOrderedSequence\": \"\", \"seqID\": \"\"}, \"prettyPrint\": false, \"mdMinimize\": true, \"options\": null, \"notices\": [{\"noticeType\": [\"error\"], \"noticeCode\": [\"400\"], \"noticeBrief\": \"InvalidInputPayload\", \"noticeMessage\": [\"An invalid payload was detected.\"], \"noticeScope\": \"Transaction\", \"messagingEntity\": \"CommonServicer\", \"additionalInfo\": {\"hint\": \"Sequence is invalid\"}}]}'",
                  "theExceptionError":"None"
               }
            }
         }
      ]
   }
}
```

**Comment by danwentworthart** [comment]
I am not 100% certain I understand your question, so please correct me if my answer is less than helpful.

Ideally:
In any case, we should not need to dig through an escaped stack trace to figure out what is happening. Proper use of the error handling framework Lachele designed could address that problem. 

Further, I believe two different scenarios would be appropriate in the context you describe:
1. For invalid json (detected in the delegation process), an error message should be returned indicating that the json object itself was poorly formed. 
2. For sequences that are deemed invalid by the evaluation service, a message should be returned indicating that the sequence is invalid. This would not be an error, but a proper evaluation response that returns 'sequenceIsValid' = false. 

In practice, I will need to dig in to the two separate cases and compare the reality to the ideal. 

Thanks again for helping us improve the API. This will be added to the list of issues that need addressing.

**Comment by ReneRanzinger** [comment]
@danwentworthart Lets ignore the user friendliness of the error message above for now. My point is that in both cases (invalid JSON, invalid Glycam sequence) the user/client provides an invalid input. Both cases use the "responses" array to communicate the issue. One creates an object with an "Error" property. The other creates an object with an "FrontEndNotice" property. That is what I find inconsistent. 

For now I will implement both. 

Also, purely semantic - but my client is not a "FrontEnd". Same is probably true for any third party tool using the API.

**Comment by danwentworthart** [comment]
I'm actually not seeing "FrontEnd" in the response you shared... Is there more that I don't see here?

**Comment by ReneRanzinger** [comment]
> 
> 
> When this bugfix is distributed, invalid input should receive some variant of the following response:
> 
> {"entity": {"responses": [{"FrontEndNotice": {"type": "error", "notice": {"code": "400", "message": "There was a problem parsing the json data: Expecting value: line 1 column 16 (char 15)"}}}]}}

That was your reply from 21.09. Thats where the Frontend part is coming from. My example from today has the "error" version and is currently returned if I provide an incorrect Glycam sequence.

**Comment by danwentworthart** [comment]
Ah, I see. Two confusing bits. 

1) I did say "some variant of the following response." The bit you see is what will vary. I can make sure frontend notice never enters the picture. That was copy pasta so I could move quickly.

2) I agree it is confusing when you request a build, to get an evaluation response and an error.  That happens because we always evaluate first. Evaluations that result in invalid sequence are services that worked as expected, a use case that you revealed to us when you had a list of sequences and a need to determine which were valid/invalid. 

However, I understand why you think it should be an error in the context of requesting a build. I will propose that we might want to add logic to suppress the evaluation response if the original request was for a build. That error should succinctly indicate that the sequence was invalid.

**Comment by ReneRanzinger** [comment]
To be honest replacing the "error" JSON up there with something that tells me 
```
"sequenceIsValid":false,
...
```
in outputs and provides more details what the actually issue is, is much better for me and tracking down the error.

**Comment by gitoliver** [comment]
@ReneRanzinger r.e. the content of the error message when there is an issue with the sequence. The older GMML level code that checks the sequence is being deprecated and isn't the best at providing good messages. In the upcoming release there is an initial sanity check that will provide messages like this (this is snippets of the C++ code, but you should get the idea):

```
"Non standard glycam residue string: " + residueString;  // You can make a 2D-SNFG graph, but not a 3D structure.
"Error: we can't parse this residue: \"" + residueString + "\""; 
"Error: sequence is empty:\n>>>" + sequence + "<<<\n" ;
"Error: sequence contains a space:\n>>>" + sequence + "<<<\n" ;
"Error: sequence cannot contain this:\'" + s + "\':\n>>>" + sequence + "<<<\n" ;  // badChars = {'\'', '_', '+', '"', '`'};
"Error: the number of [ doesn't match the number of ]. Bad branch in :\n>>>" + sequence + "<<<\n" ;
```

Once the sequence is parsed into our graph structure, then we try and convert it into a 3D structure, and you can get different messages like this:

```
"Non-integral charge (" << charge << "). You cannot energy minimize or run MD with this 3D structure.\n";
"Could find prep file and therefore cannot generate a 3D structure for this residue:  " << parsedChild->GetName() << " Glycam: " << this->GetGlycamResidueName(*parsedChild);
```

This needs to be tested in the wild, but should be a good foundation and I can improve it as we go. I'm still waiting on the changes to make it into the dev site, no idea of a timeline I'm afraid as I'm not sure of the current issues.

**Comment by gitoliver** [comment]
This has been resolved.
