### ISSUE TITLE
API: Job status webservice needed

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#25]
**Is your feature request related to a problem? Please describe.**
When using the API a job ID and a file download location is created. However the file does not exist at that point but gets created some time later after the simulation is done. Its even possible that the file exists but is not complete (in progress of been written) when it gets downloaded. There has to be a way to figure out if the simulation is done and the file completed.

**Describe the solution you'd like**
Implement a web service that consumes the job ID and returns the current status in a format (e.g. JSON). Status could be queued, in progress, finished, failed. If the job failed an error message would be needed to help debugging the reason.

**Comment by danwentworthart** [comment]
Yes. This feature is in development. We will let you know when it is finished.

**Comment by danwentworthart** [comment]
A solution exists for this now. I am writing documentation for you today, and will share that here before I close this ticket.

**Comment by danwentworthart** [comment]
This has been addressed. We have documented the solution for checking statuses of requested builds here: https://github.com/GLYCAM-Web/website/tree/master/Examples/JsonApi

Feel free to ask us for help, or give us feedback how to improve that doc.
