### ISSUE TITLE
Existing test fails in my environment

### ISSUE THREAD

**Issue by rajmehta1996** [GLYCAM-Web/website#27]
**Tool:**
Django testing. 

**Bug Description:**
List of tests failing:
"test_evaluateSequence (json_api.tests.JsonApiTests)" 
'test_status_report_view (status.tests.StatusTests)"

webdev@40cac4050f55:/website/glycam-django/glycamweb$ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........
evaluate sequence
requestString: 
{"entity": {"type": "Sequence", "services": [{"Evaluate": {"type": "Evaluate"}}], "inputs": [{"Sequence": {"payload": "DManpa1-6DManpa1-OH"}}]}, "options": {"json_api_version": "0.0.1"}}
responseDict: {'entity': {'responses': [{'FrontEndNotice': {'type': 'error', 'notice': {'code': '400', 'message': 'There was a problem submitting the request to the Sequence entity.'}}}]}}
F.
Marco Polo
requestString: 
{"entity": {"type": "Delegator"}}
responseDict: {'entity': {'type': 'Delegator'}, 'responses': [{'payload': 'Polo'}]}
..........F..
======================================================================
FAIL: test_evaluateSequence (json_api.tests.JsonApiTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/website/glycam-django/glycamweb/json_api/tests.py", line 66, in test_evaluateSequence
    self.assertEqual(str(responseDict), correctJson)
AssertionError: "{'entity': {'responses': [{'FrontEndNoti[130 chars]}]}}" != ''
- {'entity': {'responses': [{'FrontEndNotice': {'type': 'error', 'notice': {'code': '400', 'message': 'There was a problem submitting the request to the Sequence entity.'}}}]}}
+ 

======================================================================
FAIL: test_status_report_view (status.tests.StatusTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/website/glycam-django/glycamweb/status/tests.py", line 13, in test_status_report_view
    self.assertEqual(response.status_code, 200)
AssertionError: 302 != 200

----------------------------------------------------------------------
Ran 24 tests in 1.179s

FAILED (failures=2)
Destroying test database for alias 'default'...

**Comment by danwentworthart** [comment]
resolved
