### ISSUE TITLE
Oligosaccharide Select Button shows a text cursor, doesn't indicate it's been clicked. Works fine.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#33]
on dev.glycam.org/lib. Click on hmlib and then highlight any structure. The "Select" button shows a text editing cursor by default when hovered over. If you click on it, it works as expected, but the cursor through me off.

**Comment by danwentworthart** [comment]
I am guessing, without proving, that the select button is a link, not a button, which would explain that. The entire lib app needs a rewrite. I have added this to that card, so I will remember to squash it.

**Comment by danwentworthart** [comment]
Rutuja resolved this issue.
