### ISSUE TITLE
SNFG icon does not show up in online LiteMol display

### ISSUE THREAD

**Issue by Lachele** [GLYCAM-Web/website#37]
**Tool:**
test.glycam.org/cb also txt, etc.
Also DevEnv

**Bug Description:**
The SNFG icon for Psicose (and possibly others) does not show up in the online LiteMol display.

**To Reproduce:**

Enter DPsipa2-OH at test.glycam.org/txt and see display on next page.

**Expected behavior**
SNFG icon should display.

**Screenshots**

![image](https://user-images.githubusercontent.com/8740751/125443554-ccfad358-978d-4ca7-b8d4-ce3efb2d28d9.png)

**Comment by gitoliver** [comment]
This is a bug in LiteMol here: []((https://github.com/dsehnal/LiteMol/blob/master/src/Viewer/Extensions/ComplexRepresentation/Carbohydrates/Mapping.ts#L419)) See bottom of comment for paste of that section.
There are no names listed for Psi. DPsip is not present in the PDB (according to Glyfinder), so perhaps that triggered this not getting filled out for Glycam. The fix is to replace L419 with this:
               ` glycam: { colorA: '#f69ea1', names: ['0PA', '0PB', '1PA', '1PB', '2PA', '2PB', '3PA', '3PB', '4PA', '4PB', '5PA', '5PB', 'WPA', 'WPB', '0PD', '0PU', '1PD', '1PU', '2PD', '2PU', '3PD', '3PU', '4PD', '4PU', '6PD', '6PU', 'WPD', 'WPU', 'VPD', 'VPU', 'UPD', 'UPU', 'QPD', 'QPU', '0pA', '0pB', '1pA', '1pB', '2pA', '2pB', '3pA', '3pB', '4pA', '4pB', '5pA', '5pB', 'WpA', 'WpB', '0pD', '0pU', '1pD', '1pU', '2pD', '2pU', '3pD', '3pU', '4pD', '4pU', '6pD', '6pU', 'WpD', 'WpU', 'VpD', 'VpU', 'UpD', 'UpU', 'QpD', 'QpU'] }`

And recompile LiteMol. Note this issue is probably also present in Mol*, as it probably uses the LiteMol code.

```
                name: 'Tag',
                common: { colorA: '#ffd400', names: ['T6T'] },
                charmm: { colorA: '#ffd400', names: [] },
                glycam: { colorA: '#ffd400', names: ['0JA', '0JB', '1JA', '1JB', '2JA', '2JB', '3JA', '3JB', '4JA', '4JB', '5JA', '5JB', 'WJA', 'WJB', '0JD', '0JU', '1JD', '1JU', '2JD', '2JU', '3JD', '3JU', '4JD', '4JU', '6JD', '6JU', 'WJD', 'WJU', 'VJD', 'VJU', 'UJD', 'UJU', 'QJD', 'QJU', '0jA', '0jB', '1jA', '1jB', '2jA', '2jB', '3jA', '3jB', '4jA', '4jB', '5jA', '5jB', 'WjA', 'WjB', '0jD', '0jU', '1jD', '1jU', '2jD', '2jU', '3jD', '3jU', '4jD', '4jU', '6jD', '6jU', 'WjD', 'WjU', 'VjD', 'VjU', 'UjD', 'UjU', 'QjD', 'QjU'] },
            }, {
                name: 'Sor',
                common: { colorA: '#f47920', names: ['SOE'] },
                charmm: { colorA: '#f47920', names: [] },
                glycam: { colorA: '#f47920', names: ['0BA', '0BB', '1BA', '1BB', '2BA', '2BB', '3BA', '3BB', '4BA', '4BB', '5BA', '5BB', 'WBA', 'WBB', '0BD', '0BU', '1BD', '1BU', '2BD', '2BU', '3BD', '3BU', '4BD', '4BU', '6BD', '6BU', 'WBD', 'WBU', 'VBD', 'VBU', 'UBD', 'UBU', 'QBD', 'QBU', '0bA', '0bB', '1bA', '1bB', '2bA', '2bB', '3bA', '3bB', '4bA', '4bB', '5bA', '5bB', 'WbA', 'WbB', '0bD', '0bU', '1bD', '1bU', '2bD', '2bU', '3bD', '3bU', '4bD', '4bU', '6bD', '6bU', 'WbD', 'WbU', 'VbD', 'VbU', 'UbD', 'UbU', 'QbD', 'QbU'] },
            }, {
                name: 'Psi',
                common: { colorA: '#f69ea1', names: [] },
                charmm: { colorA: '#f69ea1', names: [] },
                glycam: { colorA: '#f69ea1', names: [] }
            }]
```

**Comment by cexum** [comment]
The fix here is to implement Mol*.

**Comment by gitoliver** [comment]
Works now.
