### ISSUE TITLE
longing-ladd deploy

### ISSUE THREAD

**Issue by Lachele** [GLYCAM-Web/website#38]
longing-ladd is decommissioned

longing-ladd was deployed at dev.glycam.org 
longing-ladd was deployed at test.glycam.org

Thanks for the comments

**Comment by Lachele** [comment]
Minor issue; not urgent - can the text on the antibody pane title be on one line?
![image](https://user-images.githubusercontent.com/8740751/126544415-e76e28a3-a5a9-4d81-9626-d319dd5d0a29.png)

**Comment by danwentworthart** [comment]
A fix has been pushed to the master branch of the dev env, but not deployed into production.

The font is smaller now, but never wordwraps as I resize the window from huge to tiny.

**Comment by Lachele** [comment]
Thanks.  I can add it to the deploy if desired.  I'm ok with it if it goes into the next.

**Comment by Lachele** [comment]
longing-ladd is decommissioned.
