### ISSUE TITLE
Invalid sequence result into strange PDB file

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#41]
**Tool:**
Web service: https://dev.glycam.org/json/

**Bug Description:**
An invalid sequence is submitted but instead of an error a PDB file is generated containing 2 atoms. This does not allow to distinguish valid sequences from incorrect one.

**To Reproduce:**
Sequence: DGlNAcb1-OH 
JSON: 
```
{
   "entity":{
      "inputs":{
         "sequence":{
            "payload":"DGlNAcb1-OH"
         }
      },
      "resources":[
         
      ],
      "services":{
         "build":{
            "type":"Build3DStructure"
         }
      },
      "type":"Sequence"
   }
}
```

**Expected behavior**
If an invalid Glycam sequence is provided an error should be generated.

[unminimized_DGlNAcb1-OH.pdb.txt](https://github.com/GLYCAM-Web/website/files/7198246/unminimized_DGlNAcb1-OH.pdb.txt)

**Comment by danwentworthart** [comment]
Thanks for pointing this out. Looking into it.

**Comment by ReneRanzinger** [comment]
Another example

DGlpNAcb1-3DGalpNAca1-3[LFucpa1-2]DGalpb1-3[DGlcpNAcb1-3DGlcpNAcb1-6]DGalpNAca1-OH

It seems it simply ignores unrecognizable residues. In this case 2 of the 7 residues are missing in the PDB

[unminimized_DGlpNAcb1-3DGalpNAca1-3[LFucpa1-2]DGalpb1-3[DGlcpNAcb1-3DGlcpNAcb1-6]DGalpNAca1-OH.zip](https://github.com/GLYCAM-Web/website/files/7199674/unminimized_DGlpNAcb1-3DGalpNAca1-3.LFucpa1-2.DGalpb1-3.DGlcpNAcb1-3DGlcpNAcb1-6.DGalpNAca1-OH.zip)
.

**Comment by Lachele** [comment]
This is probably an issue in GMML, but Dan and I will check upstream first.  Thanks for letting us know.

**Comment by gitoliver** [comment]
Confirmed to be a GMML level issue. It's already been addressed an upcoming GMML release that handles errors better. The output will look something like this:
"No residue code found in GMML metadata for residue: DGlNAcb"
"No residue code found in GMML metadata for residue: DGlpNAcb"

I'll come back and close this issue once the site is updated with these changes.

**Comment by gitoliver** [comment]
Forgot to come back to this. It's fixed and live.
