### ISSUE TITLE
CSRF Token not recognised when presented using Python

### ISSUE THREAD

**Issue by kate1711** [GLYCAM-Web/website#52]
**Tool:**
Overall, I am trying to create a python pipeline to download Glycam-generated PDB files for fully defined glycan structures contained in our GlyConnect Database. I have used the example CURL commands given in api-https.bash - this works fine. 
I then tried to generate the PDB file using python instead. The reason, I would like to create a pipeline (possibly including fetching Glycam formatted files from GlyCosmos) and it seems it should be easy enough to do with python (we have similar pipelines in place with our own GlyConnect API). 

**Bug Description:**
I can run the first curl command "curl -v -c cookies.txt -b cookies.txt https://"${HOST}"/json/getToken/" and the response is the CSRF token needed to send the second curl command. However when I use this token in the header of the second curl command (in the example, marco.json), it returns an error. 

**To Reproduce:**
# Python script as follows (where buildmarcojson is a function to "build" the json file (you could also just include it in the test file):

_import requests
from functions import buildmarcojson

response = requests.get('https://glycam.org/json/getToken/')
token = response.text
print(token)
headers = {
    "X-CSRFToken": token,
    'Content-Type': 'application/json',
}

data = buildmarcojson()
response = requests.post('https://glycam.org/json/', headers=headers, data=data)
print(response.text)_

The response given by the above:
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>
  <p>You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>
  <p>If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for &#39;same-origin&#39; requests.</p>
</div>
<div id="explanation">
  <p><small>More information is available with DEBUG=True.</small></p>
</div>
</body>
</html>

**Expected behavior**
Return PDB file of a glycan

**Screenshots**
See code & output above

**Device & OS Details**
Dell Latitude 7410
Ubuntu 20.04.3 LTS (64bit)
Intel Core i7-10610U CPU (8 x 1.8 GHz)
Python 3.9

**Additional context**
The curl commands given in the example bash file works perfectly, for all three json tasks (marco.json, evaluate_sequence & build_sequence).

**Comment by danwentworthart** [comment]
Thank you for sharing this. Our current plan is to address how this error is handled, and then provide documentation for using the API via Python. We will respond to this ticket as we make progress.

**Comment by cexum** [comment]
Good morning I just wanted to update you with what's going on. 

There is a bug in our API that should be fixed and distributed first, which *shouldn't* take too long.

Otherwise your procedure is literally just missing cookies which need to be passed into the POST request. I am going to write some sample Python scripts similar to the bash examples and update you as they become available.

**Comment by cexum** [comment]
Okay thank you for being patient.

Attached is a set of Python procedures that are a facsimile of the bash scripts found in the website repository:

[json_api_tools.tar.gz](https://github.com/GLYCAM-Web/website/files/7706201/json_api_tools.tar.gz)

- api-https.py <url> <json>
- checkDefaultStatus.py <url> <pUUID> ## Note: temporarily defunct on glycam.org
- checkConformerStatus.py <url> <pUUID> <conformerID> ## use this one for all polling for the time being
- downloadDefaultStructure.py <url> <pUUID> <filename>
- downloadConformer.py <url> <pUUID> <conformerID> <filename>

The following steps are intended to: submit a .json request to the api; poll for the status of that request; download the resulting .pdb file(s.)

Create a directory and extract the tarball:
`tar xvf json_api_tools.tar.gz -C path_to/json_api_tools`

Test api-https.py:
`python3 api-https.py glycam.org marco.json`

Use api-https.py to submit to request to the api:
`python3 api-https.py glycam.org build-sequence.json`

Poll for status via checkDefaultStatus.py or checkConformerStatus.py:
## Note -- polling for the default structure **will always return "minimizing"** in our production environment for the time being. The hot-fix is done but needs to be evaluated in our testing environment before the code can be migrated into production
a) poll for default structure:
`python3 checkDefaultStatus.py glycam.org ab8475c8-5d6a-4351-9d96-58cb9ceb950f`
## One should poll for a specific conformer until the hot-fix for default structure polling is migrated into production
b) poll for conformer:
`python3 checkConformerStatus.py glycam.org ab8475c8-5d6a-4351-9d96-58cb9ceb950f 1ogg`

Download .pdb via downloadDefaultStructure.py or downloadConformer.py:
a) download default structure:
`python3 downloadDefaultStructure.py glycam.org ab8475c8-5d6a-4351-9d96-58cb9ceb950f out.pdb`
b) download conformer:
`python3 downloadConformer.py glycam.org ab8475c8-5d6a-4351-9d96-58cb9ceb950f 1ogg out.pdb`

**Comment by danwentworthart** [comment]
To assist a bit more, in Charles' example, he uses 2 arguments with the
download scripts. Those can be determined by looking at the response to the
initial buildSequence.json request.

Note: the response written to file is escaped.

In that response, you can search for "downloadUrlPath". There may be many,
and they contain the arguments you will want to use as their last two
folder names. For example, I found this in my response:
"downloadUrlPath": "https://gl
ycam.org/json/download/sequence/cb/
*91a82e96-896a-4f8e-b464-516da6e6f50f/1ogg/*

The final arg Charles used, out.pdb, is yours to name. It is the file that
output will be written to.

If this is still a challenge, I can make myself available to assist.

~ Dan

**Comment by danwentworthart** [comment]
We believe this issue has been fixed. If any further assistance is needed, please don't hesitate to reach out. 
~ Dan

**Comment by danwentworthart** [comment]
Just in case it is helpful, here is a link to the JSON API documentation. 
[json api doc](https://github.com/GLYCAM-Web/website/tree/master/Examples/JsonApi)
