### ISSUE TITLE
glycam.org/gp gives a 500 error

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/website#53]
**Tool:**
Glycoprotein Builder

**Bug Description:**
If we follow old links to, or type into a web browser, the following url:
glycam.org/gp

We receive a 500 error. 

**Expected behavior**
One would expect to be redirected to the working tool.

**Context**
The dev team is aware of this issue. We created this ticket. It is easily gotten around by using either:
1. Use the link in the menu bar to the Glycoprotein Builder on legacy.glycam.org
![Screenshot from 2021-12-01 14-21-07](https://user-images.githubusercontent.com/27075406/144299760-8aeb65d0-e92c-460c-9eb3-3f2d25a43cdb.png)
2. Navigate to http://legacy.glycam.org/tools/molecular-dynamics/glycoprotein-builder/upload-pdb

**Comment by danwentworthart** [comment]
We predict this will be addressed by the end of this year. The url glycam.org/gp will be valid when the fix is implemented. This ticket will be updated to reflect that progress.

**Comment by gitoliver** [comment]
No more 500 error and there is a much clearer path to follow now.
