### ISSUE TITLE
Download page hangs/provides odd information when there are rotamers to select from.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#55]
Note this is the same odd behavour I reported for the GAG builder: https://github.com/GLYCAM-Web/website/issues/49
**Tool:**
Carbohydrate builder. From point and click, text or library. glycam.org and test.glycam.org give the same behaviour.

**Bug Description:**
If you build anything with rotamers e.g. DNeup5Aca2-4LFucpa1-OH. the downloads page has issues unless it has been built already, i.e. it's in the database, in which case it behaves fine. I.e. I can get to the downloads page which shows correct information for DNeup5Aca2-3DGalpb1-4DGlcpNAcb1-6[DNeup5Aca2-3DGalpb1-4DGlcpNAcb1-2]DManpa1-6[DNeup5Aca2-3DGalpb1-4DGlcpNAcb1-2[DNeup5Aca2-3DGalpb1-4DGlcpNAcb1-4]DManpa1-3]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH as it was already built. You can select to build all 64 rotamers on actual, they already exist. Perhaps during testing I'm not sure when this was generated. 
See video for issue. If you build e.g. DNeup5Aca2-4LFucpa1-OH you get to the Downloads page and it hangs on Minimizing. No default 3D structure is displayed. If you click on the eye symbol it then says Minimized Yes in the LiteMol box, while the status is still Minimizing. The seems to never complete >20 mins so far.

**Expected behavior**
Build a 3D structure without rotamers to see expected behaviour. Hard to give an example that then won't pre-exist, but vary the DGalpb1-2DManpa1-OH b1 and a1 to a1 and b1, or the Gal/Man to Glc. Actually they seem to be hanging now too. I'll comment later as to whether this is because the queue is full or they are bugged now too. 

Video of issue:
https://user-images.githubusercontent.com/17079588/146812105-d2212943-82ee-47f2-b85e-2840c2f148bb.mp4

**Comment by gitoliver** [comment]
The behavior was a combination of the queue being overwhelmed by lots of job submissions and a bug in disabled buttons being selectable. We could reproduce the button selection issue in our local dev envs and Dan has pushed a fix that will make it's way through. 
I was unable to reproduce the carb not showing in LiteMol on the downloads page. We will test once a website gets spun up with an empty queue.

**Comment by danwentworthart** [comment]
In my testing (local tests only), I did test with DNeup5Aca2-4LFucpa1-OH to verify that it would not hang up, and it successfully completed all minimization and conformer building. I will like to see this confirmed in production, but then maybe we can close this issue.

**Comment by danwentworthart** [comment]
Tested in production, raging-redfield. Created a new structure, watched it progress through minimization and each following step. Closing ticket.
