### ISSUE TITLE
Selected rotamers doesn't go to zero when all rotamers for a linkage are unselected, if there are other linkages present in the table.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#56]
**Tool:**
glycam.org and in my development environment. Same issue on GAG and beta carb builder.

**Bug Description:**
 When selecting rotamers, if you unselect all rotamers for a linkage it still gives number of rotamers as 1. See image. This should be 0 whenever the number of rotamers selected for any linkage goes to 0. 
![image](https://user-images.githubusercontent.com/17079588/146915258-40b4c79e-54e7-41a9-9d36-56f593a919b3.png)
Note that it will still build a single rotamer, and uses one of the rotamers even though it's unselected.
Note that it does eventually go to zero if you unselect for all linkages, so the logic is correct if there is only one linkage in the carb.

**To Reproduce:**
Build any structure with more than one linkage with multile rotamers, e.g. DGlcpb1-6DGalpb1-6DGlcpa1-OH

**Expected behavior**
The number of selected structure should go to zero whenever there are no rotamers selected for any of the linkages.

**Comment by gitoliver** [comment]
Dan this can wait until Jan.

**Comment by danwentworthart** [comment]
Selected structures gives the total for the entire table. You have gg selected for the first linkage. The way the code interprets this, is that you have requested a structure with gg for linkage 1, and you don't care what is set to linkage 2. 
Are you implying that if any single row lacks a selection, then zero selected structures is the answer?

**Comment by gitoliver** [comment]
Yes.

**Comment by danwentworthart** [comment]
OK, that can be done.

**Comment by danwentworthart** [comment]
I was able to resolve this today.
