### ISSUE TITLE
Names of downloaded files is cut off for certain sequences

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#57]
**Tool:**
glycam.org/txt with DGalpNAc[4S,6S]b1-4DGlcpA[2S]b1-OME. Any carb building tool has this behaviour

**Bug Description:**
When you get to the download page, the file name is 4ogg_DGalpNAc[4S

**Expected behavior**
The file name should either be a hash, or the full name. I suspect the comma is causing an issue.

![image](https://user-images.githubusercontent.com/17079588/147068110-861a6daf-be4b-4405-8e1b-589447ee5f04.png)

**Comment by danwentworthart** [comment]
Good eye. Thank you.

**Comment by danwentworthart** [comment]
Fixed in commit 88611816b01faf3dd569c0e09b5d3af7145c016a
Not deployed to production yet.
