### ISSUE TITLE
Long sequence failing to build in LiveTest tense-tacha.

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/website#61]
**Tool:**
Carbohydrate Builder - only in production: tense-tacha

**Bug Description:**
Long structures timeout before the cb Options page receives a gems response. No errors are thrown.

**To Reproduce:**
1. Go to test.glycam.org/txt
2. Enter this sequence:

DNeup5Aca2-6DGalpb1-4DGlcpNAcb1-6[DNeup5Aca2-6DGalpb1-4DGlcpNAcb1-2]DManpa1-6[DNeup5Aca2-6DGalpb1-4DGlcpNAcb1-2[DNeup5Aca2-6DGalpb1-4DGlcpNAcb1-4]DManpa1-3]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH

3. Options page times out with a 502 error.

**Expected behavior**
We expect the page to load with a default, unminimized structure showing in LiteMol.

**Additional context**
Remember, this does not happen in the devEnv.
I tried these things:

1. website logs confirm that a valid request was submitted via json_api.py submit()
2. gems logs look unused. I set the env var to 'debug' but it looked like it had no effect, or the logic fails to reach gems.
3. the only container I found that had grpc delegator in the name had a prefix of "archive", none contained "tense".
4. there was a django container with "tense" in its name.
5. there was another django container with "archive" in its name, that reported itself as (unhealthy).
6. the django logs for the archive grpc delegator only showed this:
```
webdev@homer:/website/DOCKER/GLYCAM/LiveTest/V_2> docker logs 1461814d97bb
Hello from json_server.py JSON_Error_Response()
About to call serve.
Starting to serve JSON API as GRPC.
Starting sleepytime.
Starting sleepytime.
Starting sleepytime.
Starting sleepytime.
Starting sleepytime.
Starting sleepytime.
```

**Comment by Lachele** [comment]
My best wild guess is that it's timing out somehow since shorter sequences work.  

I'll pull in the newest code and work from there.

**Comment by danwentworthart** [comment]
There seems to be a hiccup somewhere in returning a response from the grpc delegator container to the django python container. We are not yet certain what is causing the response to be slow, but it does eventually happen, so the communication channels have what they need.
I will rewrite the logic on the cb options page so that it can load first, then send the request via javascript and handle slow responses gracefully.
A separate push will be needed to determine why the response is taking so long when a test in the grpc delegator container seems to happen almost instantly.
