### ISSUE TITLE
Citation link in carbohydrate builder scenario is wrong

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#62]
**Tool:**
Go to 
https://glycam.org/portal/scenario_page/a402190c-b3f2-4c99-b2ce-66008a078a14
Scroll down to citations.

**Bug Description:**
[1. Kirscher, et al., J.Comput. Chem.. (2008) 29, 622-655](https://academic.oup.com/glycob/article/26/7/772/2388959)
This is the wrong link, the text is good and it links to a paper from our group, but the wrong paper. 

**Expected behavior**
It should link to https://doi.org/10.1002/jcc.20820

**Comment by cexum** [comment]
Dan said: "handled by fixture data of the portal app."

**Comment by gitoliver** [comment]
How is this going to be fixed? It still has the wrong behavior on test.

**Comment by danwentworthart** [comment]
Yesterday we confirmed that the incorrect link is right there in the json fixture data. Charles requested this task, and it should be as simple as putting the correct link into the fixture data for the Portal app, committing that edit to git and then distributing from there.

**Comment by cexum** [comment]
@gitoliver fix is up on web-test
