### ISSUE TITLE
What glycans bind to my protein scenario has some bugs

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#63]
**Tool:**
The "What glycans bind to my protein?" scenario.

**Bug Description:**
Two issues:

1. The Citations header appears once for each link. The links are good. See image:
![image](https://user-images.githubusercontent.com/17079588/163847124-6b4a4135-1d86-43da-9e9c-7da560209d38.png)

2. The link to Glyfinder under "Learn More" is borked. 

**Expected behavior**

The Glyfinder link should link to here: https://glycam.org/portal/scenario_page/868c06e9-42f2-468f-9806-094ca9095254
The Citation header should only appear once.

**Comment by danwentworthart** [comment]
I fixed the redundant headers. On to the links.

**Comment by danwentworthart** [comment]
We need to discuss a proper solution for the links. Will discuss in the Webdev meeting. Urls are stored in db, but this one is Django syntax, and that is not resolving on page render.
