### ISSUE TITLE
Carb Builder Page Jittering 

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#64]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
On the carb builder if your sequence is long enough that it wraps the page jumps between showing the scrollbar on the right or not, every microsecond or so.
Another thing that causes a similar jump is if you hover over an atom in litemol and the text that appears is large, you get jumping. Again the jumping is from the rightmost vertical navbar appearing

**Comment by cexum** [comment]
We believe this is resolved on test.glycam.org.
