### ISSUE TITLE
Chondroitin sulfate buttons are not all visible when you first land on the gag builder.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#65]
**Tool:**
The gag builder at glycam.org/gag

**Bug Description:**
When I go to glycam.org/gag either by putting the link in my browser or following the link from our landing page I get to the Chondroitin sulfate tab by default. Under Monosaccharide 2 I see only 2 buttons. When I click on the Chondroitin Sulfate tab, two more buttons appear. If I start building the buttons never appear, only by clicking the tab do I get to see them.

**To Reproduce:**
1. Go to https://glycam.org/gag/
2. Look at the GlcA and GlcA(2S) buttons under Monosaccharide 2
3. Click on the Chondroitin sulfate tab.
4. Notice that deltaUA and deltaUA(2S) appear. 

**Expected behavior**
deltaUA and deltaUA(2S) should always be available/visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/17079588/164418786-e02484ac-fd09-465e-b680-9dfc67ee5bad.png)
and then after clicking on the tab:
![image](https://user-images.githubusercontent.com/17079588/164418876-140f8707-a672-4dbf-a5a7-6b14b1219a48.png)
Page reload makes them disappear again.

**Device & OS Details**
Ubuntu 20.04.3LTS and Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by danwentworthart** [comment]
Looks like the code that used to be used was deprecated. I have to figure out what it was up to and update the logic to use a more modern approach.

**Comment by danwentworthart** [comment]
The offending code, with the deprecated method in bold: 
if(i == "delta") {
        child.value = **unescape**('\u0394')+"UA";
      }
      else if (i == "delta2S") {
        child.value = **unescape**('\u0394')+"UA(2S)";
      }

**Comment by gitoliver** [comment]
This is fixed as of: understated-ujevic, which is live on glycam.org at time of closing. 
FYI for Dan, this bug is present in the legacy site gag builder too, so it might have been behaviour you introduced on purpose looking to replicate what happens there.
