### ISSUE TITLE
Unusual monosaccharide or residue combintations

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#73]
**Tool:**
Glycam API

**Bug Description:**
It seems that unusual residues (furanose residue, sulfated GlcA) cause problems. The attached file lists the case with:
Column 1: GlyTouCan ID
Column 2: Glycam sequence
Column 3: Glycam Job ID

**To Reproduce:**
Use sequence from attached file.

[monosaccharides.zip](https://github.com/GLYCAM-Web/website/files/8565622/monosaccharides.zip)

**Comment by gitoliver** [comment]
For the 6S GlcA, we don't have parameters for that, note that the 6 position is a carboxylate on GlcA so there are two oxygens there, not sure how biologically possible that is. 

For furanoses although we have nomenclature to describe more, we only have parameters for D/L:
Ara, Sor, Fru, Lyx, Tag, Psi, Rib, Xyl
(For my future reference I got this info by
grep "^0.U" GLYCAM_06j-1_GAGS_KDN.prep
and referencing the Glycam nomenclature lookup table.)
GMML should through a fairly sensible error for this, something like:
_Error thrown by the carbohydrateBuilder in gmml during construction was: Did not find prep entry for DGalfa1-2 with glycam residue code: 0LD._
I can make this error clearer to a general user that we cannot build this monosaccharide.

Some KDN1 which will work as KDN2 as per the other github issue.

This is a bug with KDNpa2-6 linkages, I'll make a separate gmml issue for it. DGalpb1-4[LFucpa1-3]DGlcpNAcb1-3DGalpb1-4DGlcpNAcb1-2DManpa1-6[DKDNpa2-6DGalpb1-4DGlcpNAcb1-2DManpa1-3]DManpb1-4DGlcpNAcb1-4[LFucpa1-6]DGlcpNAcb1-OH
