### ISSUE TITLE
Errors from gmml are no longer being reported to the user

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#74]
**Tool:**
Carb builders

**Bug Description:**
Giving an incorrect sequence no longer provides the user with a useful error from gmml. Instead we get:
500 Error Occurred. Server error, we have been alerted, please try again later 
for this:
[https://glycam.org/url/condensed/DManpa1-9DGlcpNAcb1-OH](https://glycam.org/url/condensed/DManpa1-9DGlcpNAcb1-OH
)
Or if we go to build via text and enter this sequence:
DManpa1-9DGlcpNAcb1-OH
Then we get:
There was a problem making the default sequence request: 'showRotamerOptions'
This happens with any junk sequence.
**Expected behavior**
The error that is provided by gmml should be shown.

**Comment by gitoliver** [comment]
See here from Rene:
https://github.com/GLYCAM-Web/website/issues/75
It looks like the messages are coming out of gmml ok and are in the JSON response as Rene is able to report them to us. So I guess the website has changed.

**Comment by danwentworthart** [comment]
Session cleanup logic was throwing errors because it happened before the check for errors that are contained in the response, but not thrown in a try/catch. Addressing this now.

**Comment by danwentworthart** [comment]
Fixed in commit 848d20bb36d13d51974ba9ada3b9ffafdfa1e096
Not yet deployed to production.

**Comment by gitoliver** [comment]
Now the user gets a somewhat decent error message:
_There was a problem making the default sequence request: Could not find prep entry for DGlcpNAc. GLYCAM code used to search is: 9YB_
This is available in websites versioned "vexed-vala" and later. Close once this makes it to actual (www.glycam.org)
