### ISSUE TITLE
KDN sugars

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#75]
**Tool:**
Glycam API

**Bug Description:**
Sequence: DKDNpb1-OH
Glycam Job ID: 7f3b1b06-4b36-4861-bd0d-81630dcfd9fe
Response: Cannot create 3D structure as no GLYCAM residue code was found in the GMML metadata for residue: DKDNpb

**To Reproduce:**
See sequence above.

**Expected behavior**
KDN sugars are common in plants and bacteria.

**Comment by gitoliver** [comment]
We have parameters for KDN and are close to integrating them into the website. Will close this issue when they become available.

**Comment by ReneRanzinger** [comment]
Does this mean that KDN are supported NOW?
@cexum I think it would be good to add a final comment to a ticket before closing which clarifies how/if the problem was resolved or if it was decided that its not part of the mission to work on this.

**Comment by danwentworthart** [comment]
KDN does build in my development environment. I do see that the currently
deployed versions of the website throw errors if I use them. I will reopen
this ticket until I can see things working in deployment.

~ Dan

**Comment by gitoliver** [comment]
I didn't see it the first time, but what Rene submitted in the bug ticket: DKDNpb1-OH won't ever build, should be DKDNpb2-OH. The C2 is the anomeric carbon in KDN.
DKDNpb2-OH builds on the test site, not on actual. Once we move test to actual, this can be closed.
An issue for GMML is that the incorrect DKDNpb1-OH throws an error on test, but it's incorrect/confusing and doesn't tell you that the 1 isn't available for this monosaccharide:
_There was a problem making the default sequence request: Problem with the metadata found in gmml for this linkage. The number of identified rotatable dihedrals: 2 is greater than the number of metadata items: 1 found for this linkage: Residue_linkage Index: 93877580155488, Name: DKDNpb1-1ROH, NumberOfShapes: 1, ids: 0Kn_A_2_?_?_?@C1 -- ROH_A_0_?_?_?@O1 O6, C2, C1, O1: -17.5039. C2, C1, O1, HO1: -55.1927._

**Comment by ReneRanzinger** [comment]
@gitoliver good catch. I missed that part. We will fix that in GlyGen. If the linkage 2 version builds you can close the ticket.

**Comment by gitoliver** [comment]
It works!
