### ISSUE TITLE
Exception for G50531HE

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#76]
**Tool:**
Glycam API

**Bug Description:**
Sequence: DNeup5Aca2-8DNeup5Ac[9A]a2-3DGalpb1-3DGalpNAcb1-4[DNeup5Aca2-8DNeup5Aca2-3]DGalpb1-4DGlcpb1-OH
Glycam Job ID: 926e081b-6a29-41f7-ba26-4cdb9174614f
Response: carbohydrateBuilder constructor caught a throw type that was not anticipated. Pretty please report how you got to this to glycam@gmail.com.

**To Reproduce:**
See sequence above.

**Comment by danwentworthart** [comment]
I was able to confirm this has been fixed.
