### ISSUE TITLE
Internal errors

### ISSUE THREAD

**Issue by ReneRanzinger** [GLYCAM-Web/website#80]
**Tool:**
Glycam API

**Bug Description:**
Sometimes (1501 cases out of 6000) the submit job returns with an JSON describing something which seems to be an internal error. An example is attached. This does not seem sequence related since resubmitting will result into a valid job creation. The attached example has a sulfate but there are also structures without that have the same issue.

**To Reproduce:**
Arbitrary.

**Expected behavior**
Job creation.

[output.zip](https://github.com/GLYCAM-Web/website/files/8566486/output.zip)

**Comment by danwentworthart** [comment]
I looked at the error. The important clue is here: 
""theStandardError":"b\"terminate called after throwing an instance of 'std::runtime_error'\\n  what():  Linkage numbered 6 not found in linkages for this carbohydrate\\n\\n\""
This is thrown in gmml, but needs to be handled, not just thrown. 
Preston spotted where: 
error from line 334 of carbo builder cpp

Thanks again for spotting these.

**Comment by gitoliver** [comment]
There were two separate issues here. One is that the submitted sequence is good, but when the sequence is reorganized and labelled by gmml it creates garbage. This garbage then causes the error that gets thrown but not handled correctly (second issue). Both of these should be solved now. The backend that handles sequence labeling and ordering has been replaced, and future errors should be caught and handled in the right place now (gems level). These fixes will become available with the next release. I'll close this issue once that gets to glycam.org, just writing this note now to remind myself that it's fixed. For reference the fixes are in https://github.com/GLYCAM-Web/gmml/commit/c562df11eeb435184b4460e300aee1b239e619a0

**Comment by cexum** [comment]
@gitoliver May we close this issue?

**Comment by gitoliver** [comment]
Yes this is resolved.
