### ISSUE TITLE
Mild: Both 3D structural libraries and Oligosaccharide libraries throughout the site. 

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#83]
**Is your feature request related to a problem? Please describe.**
We use both terms: 3D structural libraries and Oligosaccharide libraries throughout the site. 

**Describe the solution you'd like**
Either term is fine, but only use one term.

**Comment by danwentworthart** [comment]
Addressed locally. Will distribute after 2-db solution.
