### ISSUE TITLE
Navigation buttons in the CFG libs app do not work.

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#84]
**Tool:**
https://glycam.org/lib/load/cfglibs/

**Bug Description:**
Scroll down and click on the navigation buttons that should change the page. Instead the number you click will show up in the search bar, and the page will stay on the same page.

**Expected behavior**
There are ~512 glycans in that library, so you need to be able to navigate to the rest.

**Comment by danwentworthart** [comment]
I wonder if this was impacted by the Django update. Thanks for noticing.

**Comment by danwentworthart** [comment]
Good catch. After assessing, I see a host of issues that need addressing. Starting a deeper assessment.

**Comment by danwentworthart** [comment]
Fixed several issues. These fixes are not yet distributed.
