### ISSUE TITLE
LiteMol on options page does not show large default structures

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#85]
**Tool:**
Any carb builder.

**Bug Description:**
When you build a large sequence e.g. DManpa1-2DManpa1-6[DManpa1-2DManpa1-3]DManpa1-6[DGlcpa1-2DGlcpa1-2DGlcpa1-2DGlcpa1-3DGlcpa1-3DManpa1-2DManpa1-2DManpa1-3]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH
Even if you've built it before, the default structure does not get loaded into litemol on the options page. Instead you get a message in LiteMol: Molecule from URL: running, 
After ~30 seconds, the molecule will appear but in the meantime it doesn't look like anything is happening. It does show up immediately if I move onto the download page, and everything else is fine. It might be looking for the molecule too quickly, and then not retrying for too long?

**Screenshots**
![image](https://user-images.githubusercontent.com/17079588/166217073-13fa6790-6c2a-4328-9d13-a474c5454692.png)

**Comment by danwentworthart** [comment]
Optimization pass is in the queue. 
I read a slack post from Lachele that the default request is building all possible (maybe she said likely?) structures. That is worth looking at, in case it is waiting for all those builds before responding.
However... This is a good opportunity to make it more obvious to the user that we are working on the build. Might as well use the opportunity to do more than just the little red note in litemol.
GitKraken card assigned: WEB-457
