### ISSUE TITLE
Glyfinder is not showing errors or warnings when I click on them

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#86]
**Tool:**
glycam.org/gf click on DManpNAc and click search

**Bug Description:**
For the entry in 1BCS, if I click on More and then Errors or Warnings nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/17079588/166217355-4b6d8a9a-e545-41b1-875b-9c3b53e8080a.png)

**Comment by Dave-Montgomery** [comment]
I found and fixed the issue, it'll get pushed with all of my changes (hopefully) today
