### ISSUE TITLE
Long carbohydrate chains never complete. Hang indefinitely

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#88]
**Tool:**
Carb builder

**Bug Description:**
DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-OME

And lengths of over ~20 monosaccs never complete. 

Reply to email thread "long chain of Carbohydrate (Hyaluronic Acid)" in glycam@gmail.com when closing.

**Comment by gitoliver** [comment]
@danwentworthart 
This is higher up than GMML. At that level I'm able to build:

DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-4DGlcpAb1-3DGlcpNAcb1-OME

However it does take a long time:
real	5m4.542s
user	5m4.158s
sys	0m0.136s
This is fishy and I need to look into why it's taking so long, but it does finish so I guess the website just isn't waiting long enough for a default structure to appear.

**Comment by danwentworthart** [comment]
I wonder if the same problem is causing ticket #85? I will look at these two tickets first.

**Comment by gitoliver** [comment]
I didn't define well what the failure was above, so I'm not sure what "never completes" means. This may the same bug, or something else. Long chains with options are now causing 500 errors on glycam actual when you try go from the options page to the downloads page. Specifically this one does it:
DManpa1-4[DManpa1-2DManpa1-2]DManpa1-6[DManpa1-2DManpa1-4][DManpa1-2DManpa1-3]DManpa1-6[DGlcpa1-3DGlcpa1-3DManpa1-2DManpa1-2DManpa1-3][DManpa1-2DManpa1-2]DManpa1-4[DManpa1-2DManpa1-2]DManpa1-6[DManpa1-2DManpa1-4][DManpa1-2DManpa1-3]DManpa1-6[DGlcpa1-3DGlcpa1-3DManpa1-2DManpa1-2DManpa1-3][DManpa1-2DManpa1-2]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH

**Comment by danwentworthart** [comment]
I have fixed and pushed the corrected field type for indexOrderedSequence in CbProject. This is not yet deployed to production, but is included in commit #8cb9b044e954315dc6b5b1562072062afb05f844
