### ISSUE TITLE
Broken Link: Legacy Home Page "Home" Button redirect

### ISSUE THREAD

**Issue by turdmuncher** [GLYCAM-Web/website#93]
**Tool:**
Please tell us which tool you were using when you spotted the bug. Bonus points for including the URL: this can tell us if you were using stable or beta code, which really helps us address issues.

**Bug Description:**

**To Reproduce:**
Please give us as many details as possible, so we can reproduce the bug. Bugs that cannot be reproduced are challenging to fix.

1. Go to 'http://legacy.glycam.org/'
2. Click on 'HOME' at top-left.
3. Should redirect to 'http://actual-glycam/'

**Screenshots**
![image (4)](https://user-images.githubusercontent.com/105873615/169353264-4aa661d9-5fbe-460b-ad72-0d1e3f6a02bf.png)
![image (5)](https://user-images.githubusercontent.com/105873615/169353283-457192f2-57b4-4ef6-b1b6-07b2b056776b.png)

**Additional context**
Andrew: "I suspect it is the redirect we made for nginx on actual if I remember correctly."

**Comment by Lachele** [comment]
The string substitution isn't working as expected.  The string 'actual-glycam' should be being translated into 'glycam.org' before the page info is handed to the client.  I think it used to work, but maybe not.

**Comment by danwentworthart** [comment]
Am I correct in thinking this ties to a redirect configuration of a proxy server, meaning potentially this needs to be brought to Andrew's attention?

**Comment by thecoulter** [comment]
Resolved
