### ISSUE TITLE
Remove flying banner when deployment is Actual

### ISSUE THREAD

**Issue by Lachele** [GLYCAM-Web/website#97]
Low priority:  When a deployment becomes Actual, suppress the versions banner.  See below.

URL:  https://glycam.org/status/versions/

![image](https://user-images.githubusercontent.com/8740751/175458487-7f6648c8-e8c1-4512-b50f-422e94940666.png)

**Comment by gitoliver** [comment]
Maybe related, or at least do-able in the same pass:
Download page on glycam actual has this:
Project Status : Finished.
Please back up all the important data generated here. Data does not migrate over to glycam.org

**Comment by danwentworthart** [comment]
This was committed and pushed in commit: 896c8426cbe4d5e4a1bf5e7418820297a5f7a068
It has not yet been deployed to production.
