### ISSUE TITLE
Wrong Solvent Accessible Surface Area calculation

### ISSUE THREAD

**Issue by gianMtuveri** [GLYCAM-Web/website#99]
**Tool:**
Glycoprotein Builder https://legacy.glycam.org/tools/molecular-dynamics/glycoprotein-builder/upload-pdb

**Bug Description:**
SASA= -1 is calculated for all the glycosylation sites. I could not proceed with the glycoprotein builder procedure.

**To Reproduce:**
1. Go to 'http://legacy.glycam.org/tools/molecular-dynamics/glycoprotein-builder/upload-pdb'
2. Upload pdb and continue
3. Assign histidine protonations
4. See the error in the screenshot

**Expected behavior**
The tool should calculate SASA for all the sites and install the chosen glycan on the allowed sites.

**Screenshots**
![SASAerror](https://user-images.githubusercontent.com/115008411/193843834-c9edfb09-337e-4756-af5e-70aea2d24a50.png)

**Device & OS Details**
Ubuntu 22.04.1 LTS 64-bit

**Additional context**
The protein is big, around 4500 amino acids. Preprocess step manages the file just fine. 

Here the pdb file:
[protein.pdb.txt](https://github.com/GLYCAM-Web/website/files/9708500/protein.pdb.txt)

I verified the SASA for the Asn residues is non-zero with Pymol.
I tested different histidine configurations but it doesn't seem to be related to the result.

**Comment by gitoliver** [comment]
Try uploading the individual chains and see if that helps. I wonder is the size maxing out what naccess can handle.

**Comment by gianMtuveri** [comment]
The problem was indeed due to the protein dimensions. Thank you for the hint!

**Comment by cexum** [comment]
Is this a bug or may we close this ticket?
